### ISSUE TITLE
Being shocked while having lighting ward

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#101]
As the title says im being electrocuted even after using the lighting war at level 20

I discovered it after being zapped with the sparks that destruction and divine storm produce . And after fighting against an incandescent husk.

**Comment by Ignaramico** [comment]
Tested other wards
Fire ward does protect you against fire, but not from the heat (idk if its intended but the descriptions make one believe you are safe from heat too) tested by standing on fire.
Acid ward works as it is, tested by walking on acid
poison ward protects against poison clouds but not tear gas, tested by walking on hazy cloud and tear gas.
couldn't test cold, since i haven't found a cold lab.

**Comment by chaosvolt** [comment]
Magic Sign (from amorphous amber) version, or Paragon of The Veil version?

Main issue with electricity protection is the damage sources are so few and far in between, and so narrow a variation in damage, that it's hard to make the Magic Sign version protect against the most common electric hazard without adding full immunity. You should notice in the long run that the magic sign version reduces the damage but doesn't halt it entirely. Given how stupidly trivial it is to get full-on electric immunity on day one, no magic required (a hazmat suit will 100% oprotect regardless of damage or filth), I wonder if it wasn't really worth the effort.

Fire Ward should be doing the same thing as Flame Armor (smoke, blisters, etc not affecting you). If I recall you still overheat, but because it blocks the actual effects that come with high temps, you shouldn't be actually taking any damage, suffering any speed loss, etc. Same should be happening with Frost Armor/Ward Against Cold.

Though Ward (Cold) also has a similar issue with Lightning Ward in that the extra effect it gets over mundane cold-protection magic is almost never relevant. Only a handful of enemies, pretty much all specific to arcana, are able to deal any cold damage. It MIGHT be relevant if you play with Magiclysm too, given cold damage from spells might be a relevant threat to worry about.

Poison Ward and teargas sounds like something wonky is going on, as I set it to block the tear gas effect. If I recall, it MIGHT be unable to stop it from blinding you though, as that's a separate thing unrelated to the teargas damage and such itself (being a hardcoded part of the field code that looks for whether you have eye protection separate from mouth protection).

**Comment by Ignaramico** [comment]
Paragon version.
ohhh ok, it just took me by surprise, i thought i the wards gave you full protection against the corresponding damage (in my wishful thinking i even hoped it protected the gear in the case of fire ward).
Thanks for the clarification and time.

**Comment by chaosvolt** [comment]
No worries. I'm still pondering what to do about Lighting Ward given how narrow the available range is, I might just revert it back to full immunity as the standard, and make the Paragon version have some form of extra effect to make it desirable over the bog-standard version. It zapping you while having the version that SHOULD grant full immunity sounds odd though. Just in case I'll look at the effects and such to see if any improvements can be made overall.

**Comment by chaosvolt** [comment]
Oh wait, shit. I see what's causing this now. @korggent, @foulman the `ELECTRIC_IMMUNE` effect flag doesn't work as-is.

![image](https://user-images.githubusercontent.com/11582235/69198770-81dc7800-0afb-11ea-8597-1793892a4962.png)

Cause is the flag name in flags.json is `ELECTRIC_IMMUNE`, but the code checks for `EFFECT_ELECTRIC_IMMUNE` instead: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L4341

**Comment by foulman** [comment]
Hmm... this is no doubt because I made the code change and then alkemann worked up the json. He did all the testing as well because I don't have a dev environment/compiler set up on my end. Nobody ever did anything with this stuff since, afaik. 
I'll see about correcting it, as I also forgot to make the feather fall effect an item flag too.

**Comment by chaosvolt** [comment]
On the plus side, I was able to fix this by just giving Lightning Ward `EFFECT_ELECTRIC_IMMUNE`  as a flag, without actually *defining* that flag in JSON anywhere. C++ is weird.
