### ISSUE TITLE
Conjure shadows issues

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#103]
The conjure shadows blessings says that at lvl 20 it last 2 minutes, but after waiting 20 minutes (i tested it intervals of 5 minutes), is when you start to see the dark clouds disappearing.

And after they totally disappear, the effect of still last a bit for the the player, this can be tested casting it, then when it fades, walk in to the center of the area where you casted it and the vision is reduced and suddenly in pops to the current visibility you should have.

**Comment by Ignaramico** [comment]
screenshot of description
![Screenshot_2](https://user-images.githubusercontent.com/34730575/69916815-1e204c00-1425-11ea-8b12-b484dd50f970.jpg)

screenshot of the second issue, after walking 3 steps it reverts back to normal
![Screenshot_3](https://user-images.githubusercontent.com/34730575/69916826-3a23ed80-1425-11ea-8ea8-f895d9fddc81.jpg)

**Comment by chaosvolt** [comment]
The duration is listing the duration of the effect it inflicts on monsters caught in the AoE (blindness), field duration is randomized based on current intensity and half-life, and I THINK there was a change by @Korggent that made fields count down spell duration before half-life starts to take effect. Pinging to ask for confirmation.

Rendering issues sound like a hardcode bug though, I noticed with webs recently that the transparacney after brushing aside webs didn't fully update until after I killed a spider, no idea why (possibly because I was hitting hard enough to leave bug splatters, which is also a field).

At a bare minimum though, one thing I could do is remove the blindess effect (because 20-odd minutes of blindness is OP as fuck) or scoot it to a separate sub-spell, then if duration does indeed affect how long the field lasts, I can make the half-life super-short and rebalance around using duration to tell you more reliably how long it lasts.

**Comment by Ignaramico** [comment]
IMO is not that OP (unless the target is stationary) since if you reach melee range to any enemy it can attack like it should be (like turrets firing at point range, unless you are ranged too, the its OP at a whole new level) and enemies can find you easy enough via sound and smell. And NPC are a bit less affected by it (the y find you faster by sound than other mobs, and they arent affected in the case of stealing). i find it like a tear gas that affects everything but you, havent tested against robots though.

I just found weird that description didnt match the effect, but now i know why.

**Comment by KorGgenT** [comment]
spell duration adds to default field length, yes

**Comment by chaosvolt** [comment]
> spell duration adds to default field length, yes

Thanks. In any case, I can always wrap blindness up in basically a subspell to retain the current desired effect, then utilize duration in the main spell for accurately telling the player how long the shadows will last.
