### ISSUE TITLE
Buffs from via sword and hammer martial art

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#107]
For some reason im getting the buffs from both hammer and sword while using a sword, sames happens if you use a hammer instead of a sword. Unarmed seems unaffected
![Screenshot_2](https://user-images.githubusercontent.com/34730575/70857849-b6a1dc00-1ebb-11ea-9397-1f553df4048e.jpg)

**Comment by chaosvolt** [comment]
Update Arcana. When https://github.com/CleverRaven/Cataclysm-DDA/pull/34602 was merged, it changed how skill and damage requirements were checked for. Instead of stuff like `min_melee` or `min_bashing_damage`, you have `skill_requirements` and `weapon_damage_requirements` as more flexible arrays. In Arcana's case, this has the advantage of letting me enforce having some arcana skill to use the more anomalous abilities of the style.

A consequence however is that all the old hardcoded JSON fields were removed outright, so the code simply ignores the old JSON. Hence, the weapon-specific techniques and buffs no longer checking for the bash or cut damage of your weapon, and they don't check for skill either. The unarmed version is only exempt because the `melee_allowed` and `unarmed_allowed` booleans weren't subject to this overhaul.

Was fixed yesterday by https://github.com/chaosvolt/cdda-arcana-mod/commit/015af89cd119d77b84a8766842cffecde6309842, but do tell me if anything else comes up.

**Comment by Ignaramico** [comment]
Yup, that was the problem, sorry for the trouble.

**Comment by chaosvolt** [comment]
No worries.
