### ISSUE TITLE
Character creation fails in the world with this mod included

### ISSUE THREAD

**Issue by Razharas** [chaosvolt/cdda-arcana-mod#111]
Game version is 0.D-8574-Win64-Curses
World was created just fine, but when game tries to init it after i try to create new character on the stage of when it tries to init this mod this error pops up and it fails to proceed

src/main_menu.cpp:696 [bool main_menu::new_character_tab()] Error: item group "NC_EVAC_SHOPKEEP_misc" already defined with type "distribution"

**Comment by chaosvolt** [comment]
Please make sure both your CDDA build and Arcana are updated _before_ opening a bug report. That is an error that happens when your Arcana build is out of date relative to CDDA, due to a change in a vanilla itemgroup that I updated way back in June: https://github.com/chaosvolt/cdda-arcana-mod/commit/b4a1444388e5957c120d11989e34da6e6e46bdad#diff-21c0a19a27aa4da215042f702ce5b8a1

**Comment by Razharas** [comment]
I was actually just downloading your current master branch right from github as is instead of using a release, that was quite silly of me

**Comment by chaosvolt** [comment]
Oh wait, I see. That's the 0.D stable build, right? That'd explain why it says it's already a `distribution` instead of `collection`, I'm so used to seeing the opposite "used old version of arcana with newer build" issue. :/

**Comment by Razharas** [comment]
I downloaded latest release and its all good now, although the presence of the same id thing in the same file as the one which caused problems in the past may be some kind of oversight for all i know
