### ISSUE TITLE
Issue with loading in arcanist basements in build 10166

### ISSUE THREAD

**Issue by HeartwawyHorror** [chaosvolt/cdda-arcana-mod#113]
![image](https://user-images.githubusercontent.com/51540578/72212245-5d22d200-34a6-11ea-88f5-6ff05161431c.png)

Started fresh new world on High Tech, Low Life scenario. This occurred after chargen, and during normal gameplay.

**Comment by Senteth** [comment]
I'm guessing it might be due to the changes in build [10159](http://gorgon.narc.ro:8080/job/Cataclysm-Matrix/10159/changes), specifically the changes allowing basements to be rotated.

https://github.com/CleverRaven/Cataclysm-DDA/commit/57ca2624a60b52fe0f70e5a47df98f3f207a8d10

**Comment by chaosvolt** [comment]
That's...odd. I could've sworn basements have already had rotations for a long time. Guess I'll see what I can do to fix this. :/

**Comment by chaosvolt** [comment]
Figured it out easy enough. The way basements are set up, they somehow get spun all about even with `NO_ROTATE` added, and it turns out that the flag just needd to be re-added to basement variants that inherit from `generic_city_house_basement`

Now enjoy having vanilla load errors about missing paper shredders and a dresser itemgroup not being defined right, instead.
