### ISSUE TITLE
Veil mutations overwrite Dragon mutations but not vice versa

### ISSUE THREAD

**Issue by gwyngerlits** [chaosvolt/cdda-arcana-mod#120]
Currently you can pierce the veil after reaching threshold for dragon, causing you to lose your mark magic and be locked at level 2 sign magic. Should the mutations for Marks overwrite the mutations for Signs (as is normal for mutations of the same category, like claws, ears, skin, etc)?

**Comment by chaosvolt** [comment]
It's intended that Paragon of The Veil spells displace their Dragonblood counterparts, yeah. Essentially they're considered higher-priority instead of mutually canceling each other. PoTV spells also used to displace the equivalent Magic Signs, but this progression had to go to enable some QoL changes (seen in https://github.com/chaosvolt/cdda-arcana-mod/pull/116).

Sorry for this system being a bit of a mess mechanically.

**Comment by gwyngerlits** [comment]
Considering a lot of the marks are better for a dragon player post threshold than blessings are, it feels a bit bad to have a curious post-thresh dragon player get locked locked out of their spells for tier 2 veil spells just for using the blade. Would it be possible for only Marks and Blessings to use custom mutation categories, but leave equivalent Signs out of it (since they can be used by either anyways)?

**Comment by chaosvolt** [comment]
The main consideration admittedly was to reduce the amount of mutations cluttering up the mutation menu, since `"player_display": false` only covers the `@` menu, plus they never implemented arrow-key selecting like with the CBM menu so if you get enough mutations before you get Dragonfire, it doesn't autoassign a letter so it becomes unusuable (nevermind that this is a potential hazard in vanilla too).

Regarding this, there is something I could do to preserve this clutter reduction while also reducing the ability to accidentally mess up your collection of Sanguine Marks:
1. Make the Dragonblood threshold automatically prevent gaining Paragon of The Veil mutations, just as going Paragon of The Veil shuts down any further access to Dragonblood mutations.
2. Make it so that pre-threshold Dragonblood and Paragon spell mutations no longer cancel each other out.
3. Make POST-threshold Dragonblood and Paragon mutations mutually cancel each other instead of PoTV mutations having priority.

This would ensure that if you do post-threshold in either category, you won't be able to mess up your spell collection by acquiring mutations you can't remove, and continuing to specialize down one path will eventually purge you of the opposing path's influence.

The only issue this will have is that PoTV spells aren't tied to the mutations like Magic Signs and Sanguine Marks are, so if you pick up a pre-threshold Arcane Blessing or two, then go full Dragonblood, you'll have a few basic Arcane Blessings left in your spell list but not your mutation list. This is probably acceptable though, compared to the current status quo.

Reopening this since fixing the "can screw yourself over and render yourself unable to acquire spells you already built your character towards" thing is an actual problem.

**Comment by gwyngerlits** [comment]
1 is good if you really want to emphasize the "permanent choices" aspect of choosing a route. 

2 might be okay if you are okay with having low level spells in any category on any character. It would be nice for a dragon to have access to clairvoyance in absence of a slot for mask of insight and for veil to have access to a few spells that cost health in a pinch, but I don't really know if its against the flavor of reaching post threshold of either.

3 seems good, but its no different than 2 because it shouldn't come up as I don't think you can cross 2 thresholds without cheating.

**Comment by chaosvolt** [comment]
That was a three-step plan, rather than a series of either-or ideas. They'd likely fall apart a bit in implementation unless all three were done.

**Comment by gwyngerlits** [comment]
Ah, that makes sense.  Sounds like a good plan.  Is there a reason that veil blessings aren't lost when the mutations are lost?

**Comment by chaosvolt** [comment]
The reason for that is because of a different approach to the mutation-clutter reduction: the 30 spell-granting mutations are divided into 6 linear successions of traits, building up one after the other. Since spell class can only count one mutation as valid, linking them would cause the spells to vanish (with the only alternative being to clutter the mutation menu with 30 mutations instead of just 5).

Once I found out that I can make progression _also_ grant levels for the spells earned previously, it also got a secondary use in that it allows me to make earning PoTV mutations build up and improve the preceding spells, which is useful since I can't have them learned via spellbook, so the only other way to gain EXP for them is via cast-grinding.

**Comment by chaosvolt** [comment]
Okay, been testing trying to get this to cancel properly and so far it's...wow. It seems even if the cancellation is way farther up the mutation sequence, it wants to remove them as early as possible.

![image](https://user-images.githubusercontent.com/11582235/76795624-aab60680-6797-11ea-84ac-7f598103cf73.png)

So far it's *really* aggressive about trying to eliminate the sanguine mark mutations, gonna try another method to do this.

**Comment by chaosvolt** [comment]
And...hmm. Gaining the threshold mutation won't cancel mutations, so that won't work either...an alternative might be to push all the Dragonblood spell mutations to be post-threshold. which they used to be. Would make it less accessible (as blood effigy won't ping it anymore), but also will make it a lot easier to control this.

**Comment by chaosvolt** [comment]
Okay, I should've expected these mechanics to not work every well, so **of course** making the Sanguine Mark mutations all exclusively post-threshold mean it'll still eat your Arcane Blessing mutations, which of course means being able to cheese the restored ritual blade plus sacramental heart for infinite level-ups 

But if I, instead of making Sanguine Marks all exclusively post-thresh, instead restored the **other** old hack where blood effigy was unable, that means that you could only cheese the system for so long before you pick up one of those thresholds, at which point no more mutations...

Or, I could ignore this idea in favor of moving the mutagen immunity out of the threshold definition, and into the spell mutations themselves (so that using the restored ritual blade AT ALL confers mutagenic immunity, while using even blood effigy will risk being locked into a path towards Dragonblood).

But then, even if I did that, or if I did a more limited but more involved method where I told the spell mutations to permit all vanilla mutation categories but still block the opposing category, I'd also need to make the hermit's backdoor quest stuff sanity-check for the presence of Sanguine Mark mutations...

This is giving me a headache. :/

**Comment by chaosvolt** [comment]
Okay, I think I've made a potential breakthrough:
1. Pushing all Sanguine Mark mutations to post-thresh.
2. Making Dragonblood threshold gain mutagenic immunity like Paragon of The Veil does (at least to PoTV mutations).
3. Lowering PoTV's mutagenic immunity all the way down to the 1st-level Arcane Blessing mutations.

This will make it so that you can't get Sanguine Marks without already being far enough into Dragonblood to take proper advantage of them, along with also forcibly preventing you from getting any Arcane Blessings entirely (thus eliminating the issue of hitting full Dragonblood but losing Sanguine Marks to basic PoTV spells). Conversely, if you use the restored ritual blade at all, you're locked out of pursuing Dragonblood.

The only problem potentially comes up if you go pre-threshold Dragonblood a bit (like abuse blood effigy), then switch out for pursuing Paragon of The Veil. But even then, that's still better than being locked into limited PoTV progression, this way once you're in a position to decide on one or the other, you'll remain in a position where you can at least complete ONE category.
