### ISSUE TITLE
Unable to load a world with Arcana installed on CDDA

### ISSUE THREAD

**Issue by Styxel007** [chaosvolt/cdda-arcana-mod#125]
DEBUG    : Error: data/mods//Arcana/ammo_effects.json: line 4:12: unrecognized JSON object

[
  {
    "id": "LIGHTNING_JUDGMENT",
    "type":
           ^
            "ammo_effect",
    "aoe": {
      "field_type": "fd_electricity",

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 798
--------------------------------------------------------------------------------------------------------------
This is the issue that appears when I attempt to load in, any help would be appreciated

**Comment by chaosvolt** [comment]
You're using a recent arcana build with an out-of-date CDDA build. If you're using experimental, update CDDA. If you doing that and using the launcher, remember that "update game" does not touch third-party mods, you'll want to update arcana afterward too via deleting and re-installing it in the mods section.

If you're using 0.D stable, releases are here: https://github.com/chaosvolt/cdda-arcana-mod/releases But, note that if you are, 0.E stable came out literally today. Current master version of Arcana is compatible with 0.E, and I plan to set aside a 0.E release of it fairly soon since development is gonna explode with new features for me to fuck with, once https://github.com/CleverRaven/Cataclysm-DDA/pull/39154 is merged.
