### ISSUE TITLE
Error in creating new character

### ISSUE THREAD

**Issue by Swordhard** [chaosvolt/cdda-arcana-mod#134]
![Error](https://user-images.githubusercontent.com/63740387/79365582-2f27b080-7f21-11ea-97a1-27f755f8c170.png)

**Comment by chaosvolt** [comment]
You're either using outdated Arcana with a newer build of CDDA, or using master branch of Arcana with a stable build of CDDA. If the former, reminder that the launcher's "update game" option does not touch third-party mods, you have to delete and reinstall the mod from the mods section. If the latter, relases for 0.D and 0.E stable are here: https://github.com/chaosvolt/cdda-arcana-mod/releases

Original issue report was https://github.com/chaosvolt/cdda-arcana-mod/issues/129, fixed by merging https://github.com/chaosvolt/cdda-arcana-mod/pull/130
