### ISSUE TITLE
Passing the Dragonblood threshold blocks levelling up spells with pattern scrolls

### ISSUE THREAD

**Issue by LordPancitoFresco** [chaosvolt/cdda-arcana-mod#140]
Im pretty sure thats what its preventing my character from levelling up spells now. After the lastest update which fixed my last report they did work and i leveled one my spells a few times, but i hadnt crossed the Dragonblood treshold yet. After doing so they dont level up anymore, or atleast i think thats the reason why they dont now. 

Also another thing that i noticed is that when you use the Sacramental Hearth your Marks only level up when you gain another mark that you didnt had, so if you have all the marks and all the possible dragonblood mutations and keep using the Sacramental Hearth you are just wasting blood essence since it does nothing, but i assume it should at least level up 1 mark for those 10 blood essence, this problem may actually not be a problem and its intended but it seems weird since the message you get when you use the S. Heart when it does nothing implies that it actually did something.

Im not sure if what i said in the title its the actual reason of them not levelling up now, so im adding the template of my actual character, which already comes with the scrolls on his inventory, maybe you can figure it out if im wrong with the reason of why they dont work.
[arcana bug character.zip](https://github.com/chaosvolt/cdda-arcana-mod/files/4568547/arcana.bug.character.zip)    (the .zip has an image showing the mods that i use, just in case)

Sorry if im being *THE BIG ANNOYING* but this is my favorite mod in ccdda.

(also the horns sprite kinda clip with the mohawk hairstyle on deadpeople tileset ¯\\_(ツ)_/¯ )

**Comment by chaosvolt** [comment]
That's partly intentional. It currently prevents gaining Magic Signs that do similar things to what the Sanguine Marks grant. They should still be allowing pattern scrolls that don't compete with Sanguine Marks, however. That said, I guess I could remove that feature since it doesn't properly make them mutually exclusive, but part of it is also to reduce mutation menu clutter.

The main issue is that adding the workaround for leveling up means I can't set Sanguine Marks to simply remove any competing Magic Signs. So if you started with a given Magic Sign and go post-thresh Dragonblood, you can't level it up with pattern scrolls but it's still usable.

As for the sacramental heart, that one's an issue with mutagenic items in general. Eventually you run out of mutations to grant. Right now, Sanguine Marks and Arcane Blessings have limited evolution. I might go ahead and let them evolve all the way until they fully level all or most of their spells, given how slow cast-grinding it, but still hard to decide how best to implement all this. @.@

**Comment by LordPancitoFresco** [comment]
Cant you make it so that the Signs that conflict with Marks are a prerequisite to those Marks? i havent played enough to know if the Marks are supposed to be a stronger version of the Signs or not, but if they are stronger or at least longer lasting then the Mark just replacing the sign completely seems fine to me. And when you use a pattern scroll of the ones that conflict, it just gives you some xp towards that mark. Though i dont know how difficult that would be to implement and im just pulling this opinion out of my ass.

**Comment by chaosvolt** [comment]
The main issue is that removing the mutation will no longer remove the spell linked to it, basically. I'm still tinkering with it. As for Magic Signs vs. Sanguine Marks, the main benefit is that the side effects tend to play off Dragonblood's strengths and weaknesses, in others respects they tend to start off stronger but be less useful at their primary purpose when fully leveled up. Between that and costing a different resource, might be a valid reason to not have them be mutually exclusive, I suppose.
