### ISSUE TITLE
Hard crash in latest CDDA version

### ISSUE THREAD

**Issue by meelock** [chaosvolt/cdda-arcana-mod#153]
DEBUG    : Error: data/mods//Arcana/items/ranged.json: line 126:46: Invalid damage type

    "skill": "magic",
    "range": 15,
    "ranged_damage": { "damage_type": "true",
                                             ^
                                              "amount": 40, "armor_penetration": 50 },
    "dispersion": 150,
    "durability": 6,

    FUNCTION : bool main_menu::load_character_tab(bool)
    FILE     : src/main_menu.cpp
    LINE     : 1146

Then the game quits back to main menu when you press I.
Probably related to: https://github.com/CleverRaven/Cataclysm-DDA/commit/c11de4170471644f03b9ba77015c3eae35b46008 or maybe https://github.com/CleverRaven/Cataclysm-DDA/pull/43221/commits/dd18856422a2f445d181f67002234457fa443fd9

**Comment by meelock** [comment]
Also
 DEBUG    : Error: Invalid enum string 'true' for '11damage_type'

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1146

**Comment by chaosvolt** [comment]
Ah, weird. Of course they'd be fucking around with damagetypes again.

**Comment by chaosvolt** [comment]
Tested the changes in the latest commit and it fixed load errors, at least on a new world. When you update arcana again, do tell me if the save loads properly, it should since damagetype wouldn't be preserved by anything that gets saved like `relic_data`, but you never know.

Sadly I'll be out and about soon so won't be able to check up on this until later today.
