### ISSUE TITLE
Suggestion: additional dragonblood mutations

### ISSUE THREAD

**Issue by Stretop** [chaosvolt/cdda-arcana-mod#155]
Hi, chaosvolt.

Absolutely love your mod. Especially dragonblood mutation line. However I think there are two aspects that can be added here to further improve this particular post-threshold phenotype:

1) Eyes. Dragons are famous for their stare: both for eye-sight and for powers of charming and domination. So I suggest adding mutations similar to eyes from vanilla's lizard mutation line (like night vision and reptilian IR) and also granting special spell for dominating NPCs, instantly making them your followers (flavourful but not often used - NPCs are a rare sight in-game - thus not exactly OP).

2) Dragon hoard. Much like vanilla's post-threshold spider mutants need web-nests to sleep, post-threshold dragonbloods probably should gather a hoard to sleep soundly. Such a hoard can be estimated by how much silver/gold/platinum is present on the tile the dragonblood is trying to sleep on (and on later variant of mutation - within one and even two tiles from the sleeping tile). Sleeping within such a hoard can give bonuses depending on the level of this "dragon hoarder" mutation and total amount of precious metal in the hoard. Bonuses I can think of:
1) Hunger/thirst freeze while sleeping (like Waste Recycler CBM).
2) Faster regeneration/limbs mending without splints while sleeping.
3) Ignoring light level while sleeping (like blindfold).
4) Ignoring temperature while sleeping.
5) Ignoring noises while sleeping (like noise-cancelling gear).
6) Cleansing from poisons/infections/parasites while sleeping.
7) "Hoardsense" - wake up immediately if there are hostiles within certain range of the hoard you are sleeping in (like Alarm CBM).
8) (At a very high level) Being able to teleport back to the hoard where you were last sleeping.
All in all - mostly utilities, that can be gained by other means, but more flavourful.

**Comment by chaosvolt** [comment]
Basically every one of those isn't really doable without hardcoded stuff. Vision multipliers would be nice, but I'd like it to be a tradeoff like with Ursine Vision. Giving then a hypnotic ability would be interesting, but it would clash a bit with the mutation getting persuasion penalties in exchange for intimidation bonuses. In addition, Sanguine Mark: Malevolent Gaze does a good job of representing the idea of an imposing gaze being used as a spell effect.

As for stuff involving a hoard, basically all of those features...really won't be doable mechanically, far as I can tell. Even then, the hoard idea is one I'm a little reluctant to rely on. If anything it'd feel a bit comical to be compelled to act like a magpie upon becoming a dragon, especially since the general theming of what perks Dragonblood grants paints a much more animalistic and alien picture. In particular, the fact you gain a selection of spells from going post-thresh Dragonblood is meant to hint at the creature you're emulating being otherworldly.

That said, there are a few ideas I've wanted to so, SOME of which I potentially can do now.
1. Vision stuff. I'm fairly certain vision modifiers are still hardcoded, but they'll likely be one of the next targets for JSONization if/when mutation features get more JSONizing. Ideally, like I said above, it'd be a shift to encourage activity at night. Immunity to blindness might also be a useful side perk to spring from that idea, something that can be done using effect-from-enchantment-from-mutations.
2. Hearing. One idea I would like would be something that reduces your overall hearing range in exchange for having the sounds you DO hear either reveal more useful info, or at least be placed more accurately to better track the source. That wouldn't even remotely be doable without it being hardcoded in, only the hearing modifier itself is doable right now. An alternative would be to reduce hearing modifier in exchange for being completely immune to being deafened, again something doable using enchantments. Either way, would fall more in line with the "alien biology" theme than anything thematic, i.e. hinting at more reptilian auditory organs or something entirely more abnormal. immunity to blindness and deafness would have a slight thematic tie-in with the fact that the Sanguine Order were the ones researching this particular attempt at transhumanism, given the main magic item used by their number-one enemy has a flashbang effect...
3. One thing I'd like to do, something completely impossible without hardcoded support, would be to tie the character's healing rate and stamina regen to metabolic activity level, instead of being fixed. This would make it so that they'd heal fastest and get the most stamina recovery when active. Not only would it suit the playstyle Dragonblood pushes you towards a lot better (easier to be aggressive when you gain noticeable healing while wading through bodies), but it'd also again be a good way to highlight that a Dragonblood's metabolism is now closer to a biological furnace than anything used a natural animal would use.

**Comment by Stretop** [comment]
Fair enough. A few points though.

- Dragonblood's metabolism is now closer to a biological furnace than anything used a natural animal would use

Hm, about this: shouldn't this metabolism eventually result in immunity to infections, ambient diseases and parasites? As in "they are cooked alive way before getting opportunity to become active". At least while you are overly active.

- easier to be aggressive when you gain noticeable healing while wading through bodies

Then you would still need splint-less extremities mending. And maybe some variant of "Eater of the Dead" mutation - for the same reason Chimera line gets it - to fuel your rampage.

- If anything it'd feel a bit comical to be compelled to act like a magpie upon becoming a dragon, especially since the general theming of what perks Dragonblood grants paints a much more animalistic and alien picture.

Less a magpie and more an alchemist, really. Getting gold from lead and all that. And I have a question for you: why most ritual tools (like offering chalice and silver athame) are necessarily made from precious metals? Is it just (boringly) due to cultural presuppositions, or is it due to those metals actually being good conduits to otherworldly energies?

- An alternative would be to reduce hearing modifier in exchange for being completely immune to being deafened, again something doable using enchantments. Either way, would fall more in line with the "alien biology" theme than anything thematic, i.e. hinting at more reptilian auditory organs or something entirely more abnormal. immunity to blindness and deafness would have a slight thematic tie-in with the fact that the Sanguine Order were the ones researching this particular attempt at transhumanism, given the main magic item used by their number-one enemy has a flashbang effect...

That's... absolutely awesome ^_^
However, this still presents problems with ever-seeing and ever-hearing character trying to sleep in less than completely dark and soundless environment (like near a lab that has a turret that guns down the same group of zombies again and again).

**Comment by chaosvolt** [comment]
> Hm, about this: shouldn't this metabolism eventually result in immunity to infections, ambient diseases and parasites? As in "they are cooked alive way before getting opportunity to become active". At least while you are overly active.

I've considered that, yeah. Might be a good addition to add since most of those exist as mutation flags now, and if not enchantments can tack on a hidden flag to do the same thing. Tying it to activity level sadly wouldn't be doable, so it'd end up being a static, always-on effect. Plus, gameplay-wise it might warrant rebalancing the Revenant Blood spell since that'll make some of its uses obsolete. If the heat still lets fungal spores in, then the spell would still have at least some utility.

> Then you would still need splint-less extremities mending. And maybe some variant of "Eater of the Dead" mutation - for the same reason Chimera line gets it - to fuel your rampage.

I don't know if splint-less mending is a thing, but I can at least make use of mending_modifier to make splints fix your limbs faster. Eater of The Dead still has hardcoded effects, but copy-from improvements mean I can make it a Dragonblood mutation now. It would admittedly run into the same issue where I'd need to tweak Revevant Blood due to its main niches becoming obsolete, but if I focused on stamina other metabolic side effects, plus retained the emphasis on fungal immunity, that might be a useful way to make the spell useful again...

> And I have a question for you: why most ritual tools (like offering chalice and silver athame) are necessarily made from precious metals? Is it just (boringly) due to cultural presuppositions, or is it due to those metals actually being good conduits to otherworldly energies?

My main lore thought was that a magic item's form is part of what helps bind the effects applied to it, with symbolism and motifs effectively being similar to mnemonics and ritual, grounding the immaterial and otherworldly in reality and making it more accessible to its users. Material choice would be part of that, having certain symbolism and thus grounding the effect the item uses in something easier for its user to wrap their head around (same reasoning why History of Alchemy is the easier skillbook to learn from, it's the only one with strong ties to a real-world practice).

> However, this still presents problems with ever-seeing and ever-hearing character trying to sleep in less than completely dark and soundless environment (like near a lab that has a turret that guns down the same group of zombies again and again).

That one's an annoyance, yeah. At least the usual items to sleep through noise should still be usable, since Swept-Back Horns still allow soft gear, and fairly certain the makeshift earmuffs count as such. Tying effects like "can't hear" to the "attempt to sleep/asleep" activities definitely would be nice for QoL but not sure if there's be any real way to implement them. Otherwise one might have to resort to using Heavy Sleeper instead.

**Comment by Stretop** [comment]
> I don't know if splint-less mending is a thing,

It is a thing for "REGEN_LIZ" mutation. I do not see how it is done in the JSON, however, so it seems to be hardcoded to this mutation.

> I'd need to tweak Revevant Blood due to its main niches becoming obsolete

How about giving it the same mechanic as "Acid Blood" mutation but with different damage type? Like "Heat" or maybe even "True". Or reducing blood loss?

> Otherwise one might have to resort to using Heavy Sleeper instead.

It would have been nice to have a mutation that combines effects of a "Heavy Sleeper" one and an "Alarm" CBM. But this cannot be done easily.

> At least the usual items to sleep through noise should still be usable

Wouldn't deafness/blindness immunity override them?

**Comment by chaosvolt** [comment]
> It is a thing for "REGEN_LIZ" mutation. I do not see how it is done in the JSON, however, so it seems to be hardcoded to this mutation.

The JSONized element of `REGEN_LIZ`, the "faster mending when splinted" bit, is accessible at least. That's better than nothing.

> How about giving it the same mechanic as "Acid Blood" mutation but with different damage type? Like "Heat" or maybe even "True". Or reducing blood loss?

Not easily done. Acid blood's effect is hardcoded, and blood loss is only sorta doable. There's a probably that basically grants immunity to low enough level of blood loss, My Sweet Cataclysm uses it to make sugarkin completely immune to bleeding. That would be a better fit for scales representing harder-to-injure skin rather than mocking up a "wounds close faster" effect. And the damage resistance you get from scales already would cover that.

Instead, I like the idea of its metabolic downsides perhaps lending itself to maybe playing off the existing upsides of Dragonblood. It could be reflavored as making the character's inner fire go into overdrive, increasing their stamina and other perks at the expense of faster hunger gain while it's in effect, burning out any trace of parasites or fungal infection as a side effect.

> Wouldn't deafness/blindness immunity override them?

Actually shit, you're right. I don't know if you can properly add immunity to flashbang effects using what methods currently exist, without it also preventing you from being able to use a blindfold and ear plugs. That's actually, sadly, a good argument against implementing those abilities. Especially since I can't think of any way to ensure you're immune to flashbangs WITHOUT almost making blindfolds not work, something that wouldn't make sense.

**Comment by chaosvolt** [comment]
Closing for now, tinkering with at least implementing a couple of the things I can actually do, for the time being.
