### ISSUE TITLE
Why was this move out of the core?

### ISSUE THREAD

**Issue by linonetwo** [chaosvolt/cdda-arcana-mod#158]
As long as you are still maintaining it.

**Comment by chaosvolt** [comment]
Long story that amounts to a year of mistakes on my part, together with the main developer and I being horribly abrasive and abusive towards each other, leading to me getting kicked off the project.

Arcana (and all my other mods) languished for quite a while afterward with no maintainer because I was basically the only contributor that made a habit of checking that in-repo mods actually work, until eventually I started picking them back up and maintaining them as third-party mods, with arcana being the first one to get that treatment.
