### ISSUE TITLE
Inventory error

### ISSUE THREAD

**Issue by lordmatiz** [chaosvolt/cdda-arcana-mod#162]
Clothes with pockets (Wyrmskin armor in this case) are causing errors when you try to drop items from them (multidrop / advanced inventory); the game drops 'none' instead. Error does not happen when you either 'U'nload cloth or 'w'ield said item... 

![image](https://user-images.githubusercontent.com/16430038/96853062-3264a180-145a-11eb-858a-f7a321dd0fba.png)
![image](https://user-images.githubusercontent.com/16430038/96853702-f41bb200-145a-11eb-8632-c7e7c10840be.png)

**Comment by chaosvolt** [comment]
That looks like a hardcode bug, as far as I can tell. Can you spawn in boiled leather armor (what wyrmskin armor copies from) and see if it does the same thing?

**Comment by lordmatiz** [comment]
I've checked it - boiled leather armor works normally while wyrmskin still sends errors.

**Comment by chaosvolt** [comment]
Shit, that might be a consequence of it having both pockets and being able to reload it with ammo. Does RM13 armor have pockets in addition to being fueled with plutonium? If so that might be good to test it. For now, grabbing the latest build so I'll try to test this as well, in addition to getting reference info on item lengths for the other issue.

**Comment by chaosvolt** [comment]
I'm getting different results here. I can drop items stored in the armor, whether normal `d`rop or `D`irectional drop, without any errors. However, when in the inventory screen, trying to select an item in the armor to examine them closes the inventory menu instead of opening the item screen.

I'm reworking things a bit and might just make tool armor not use storage because, between this an other past bugs, combined with vanilla evidently actually having no examples of tool_armor with storage far as I can tell, it's becoming very clear to me that this combination of features is too buggy to trust, and a lack of vanilla usage is likely ensuring that bugs like this will hang around.

I'd advise you report an issue in CDDA proper that tool_armor is unable to properly combine being loadable with ammo with having working pockets, and note current behavior of item selection failing.

**Comment by chaosvolt** [comment]
The main problem I see here is that the only viable solution is to remove the pockets the affected items have, and this might cause load errors or other fuckery on old saves that previously had items stored inside said armors. But, at this rate this change seems necessary to prevent stuff that's ALREADY causing errors.
