### ISSUE TITLE
Crash on mod load when using latest version

### ISSUE THREAD

**Issue by saladofstones** [chaosvolt/cdda-arcana-mod#164]
DEBUG    : Error: data/mods//cdda-arcana-mod-master/Arcana/spells/spells_aftermath.json: line 86:42: invalid flags: "NO_PROJECTILE"

    "effect": "bash",
    "shape": "blast",
    "flags": [ "SILENT", "IGNORE_WALLS", "
                                         ^
                                          NO_PROJECTILE" ],
    "max_level": 10,
    "min_damage": 10,

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 861

Get this error when I try to load a world.

**Comment by chaosvolt** [comment]
Are you using 0.E stable or 0.E experimentals? If the latter, then you're using the latest master of Arcana with an older version of CDDA, and should use the 0.E release instead: https://github.com/chaosvolt/cdda-arcana-mod/releases

Just checked and they haven't removed that flag (which was introduced by https://github.com/CleverRaven/Cataclysm-DDA/pull/44481), so it's likely a case of new Arcana, old CDDA.

**Comment by saladofstones** [comment]
yeah that was the case, thank you for responding.

the only message I get is:

 DEBUG    : Mapgen island_temple_2 is not used by anything!

 FUNCTION : void mapgen_factory::check_consistency()
 FILE     : src/mapgen.cpp
 LINE     : 331

I don't know if it is this mod, but I get this message now, using the latest version of both.

**Comment by chaosvolt** [comment]
If you're switched to latest experimental build, just deleting obsolete.json in Arcana should do it. It's supposed to be gone ever since I deleted it due to figuring the contents of it had gone long enough that no old saves will contain anything from it, but every so often it seems people retain that file due to extracting the new folder into the old one instead of deleting the old folder to replace it.
