### ISSUE TITLE
Adapt new container

### ISSUE THREAD

**Issue by linonetwo** [chaosvolt/cdda-arcana-mod#168]
electrothermal_arc_cannon_part https://github.com/CleverRaven/Cataclysm-DDA/issues/45433

There are two errors, probably from this mod, I guess, since this is the only additional mod I installed.

**Comment by chaosvolt** [comment]
Looking at the linked issue and...hmm.

Second one I'll grab a recent build and look into, but the first one shouldn't be caused by Arcana. The group that loads the Sanguine Shrike's flintlock pouch calls for 14, as its standard: https://github.com/chaosvolt/cdda-arcana-mod/blob/master/Arcana/chargen/professions.json#L6

**Comment by chaosvolt** [comment]
Okay, something fucky is going on here, because it's saying it wants to put 30 ammo in the pouch but I've only set it to dole out 14. I would've assumed it was some nested container nonsense, like trying to put loose ammo in inventory into the pouch despite it already being full, but the profession in question doesn't HAVE any loose ammo to worry over.

**Comment by chaosvolt** [comment]
Ahah! The NPC version of the Sanguine Shrike defined the contents of their ammo pouch like this: `{ "item": "flintlock_pouch", "charges": 14, "contents-item": "flintlock_ammo" }`

Yet, despite 14 rather obviously not being 30, switching to this fixed it: `{ "item": "flintlock_pouch", "contents-group": "NC_BLOOD_MAGE_SHRIKE_ammo" }` along with defining an itemgroup for that. For some reason, reusing `bandolier_flintlock_shrike` used by the profession version had it complaining it couldn't find that itemgroup, fucking load order nonsense.

**Comment by linonetwo** [comment]
Wow, that is weird, thanks for the fix.
