### ISSUE TITLE
Seems to be a probelm with the Json

### ISSUE THREAD

**Issue by SirClarke** [chaosvolt/cdda-arcana-mod#173]
![Screenshot (7)](https://user-images.githubusercontent.com/31796878/103434061-dc367c00-4bc9-11eb-9c43-45134b260ec4.png)
![Screenshot (8)](https://user-images.githubusercontent.com/31796878/103434065-e9ec0180-4bc9-11eb-8928-5e51a56953d4.png)
![Screenshot (9)](https://user-images.githubusercontent.com/31796878/103434066-f1130f80-4bc9-11eb-8688-b0d59f71fa62.png)

Not sure what it means or if I've done something wrong...

**Comment by Enderlordalatreon** [comment]
Yeah I seem to have the same problem, prevents the world from loading.
Could be from the Kenan Modpack, so let me try it from the sauce.

**Comment by SirClarke** [comment]
Hmm odd thanks for trying

**Comment by Enderlordalatreon** [comment]
[I wonder if it's in relation to this?](https://github.com/CleverRaven/Cataclysm-DDA/commit/c51460d0e84e18e23f235b068f079ff084c359ea)

**Comment by chaosvolt** [comment]
I'll test this tomorrow and see if there's anything odd going on with the latest build.

In the meantime, make sure you're using the right version. If you're using DDA experiemental, use the standard Arcana folder. Use the Arcana_BN one if you're using Bright Nights. And, make sure you're actually getting this here, not from some random mod compilation, and also make sure you properly delete and replace the old version, don't just paste the new folder onto the old one.

**Comment by Enderlordalatreon** [comment]
> 
> 
> I'll test this tomorrow and see if there's anything odd going on with the latest build.
> 
> In the meantime, make sure you're using the right version. If you're using DDA experiemental, use the standard Arcana folder. Use the Arcana_BN one if you're using Bright Nights. And, make sure you're actually getting this here, not from some random mod compilation, and also make sure you properly delete and replace the old version, don't just paste the new folder onto the old one.

I appreciate it, I'll test BN tomorrow. Have a happy new year.

**Comment by chaosvolt** [comment]
Okay, looking at this, it looks like the cause is `fill_ter` has either broken or been depreciated. Every error I've found so far has turned out to be caused by a missing terrain definition for the specified letter, which had previously been silently calling its fill terrain as a fallback.

So this is good in the long run since it's revealing some terrain issues I would want to fix, but still a bit unusual since I can't see any sign of a commit that'd make it generate an error. About to do one final test then I'll commit the fix, and start work on testing all the other mods I'm involved in that mess with adding new mapgen files (Tankmod: Revived, Dorf Life, likely also will send PRs for Cataclysm++ and Mining Mod).

**Comment by SirClarke** [comment]
Thanks a lot, Dude keep up the great work

**Comment by chaosvolt** [comment]
No worries. Arcana and Tankmod should both be fixed, other mods to be updated tomorrow if I can.
