### ISSUE TITLE
Candle of warding not craftable

### ISSUE THREAD

**Issue by Light-Wave** [chaosvolt/cdda-arcana-mod#178]
I am using Arcana (Not Arcana_BN) downloaded at 14'th of February, 2021.
The candle of warding is not craftable, as it does not recognize a candle to be a candle. Candles were recently altered to contain wax instead of having charges, which is probably related to this issue.
A candle (0/100) _can_ be used to craft the candle of warding, but is difficult to gain access to during normal play.

**Comment by chaosvolt** [comment]
Fucking nested containers shit, from the sound of it. It shouldn't be breaking just because an item contains discrete ammo, normally an item can be used in crafting even if filled with ammo that can't be unloaded.

You should report this to DDA itself, this suggests something has been fucked up on DDA's end, because I just tested the vanilla jack o lantern recipe and it ALSO won't recognize a still-usable candle as a valid component:
![image](https://user-images.githubusercontent.com/11582235/110186584-6625df80-7ddb-11eb-8f06-c7e7b225bf96.png)

**Comment by chaosvolt** [comment]
I also tested the `NEEDS_FULL_MAGAZINE` recipe flag, no effect.

**Comment by b0urgeoisie** [comment]
my experience with this in arcana and with just the base version of the game is that if the recipe requires an item, and the recipe doesn't require charges - then you need a chargeless item. a good example would be things that need a soldering iron won't work if you have a battery loaded, you have to unload the battery. 

the issue with candles and lighters and shit is that you can't fully unload them. they're at 0/X.

**Comment by chaosvolt** [comment]
Which is contrary to the entire concept of crafting a candle of warding from a candle, as then it won't be consumed in the process. I suppose I COULD hack this in via making the player require all the tools and components to MAKE a candle, instead of calling for a candle directly. That'd at least solve the immediate arcana-specific issue, but it would do nothing to alleviate the underlying root cause.

As has already been demonstrated above, this is 100% a vanilla fuckup, and there's a vanilla recipe that is subject to the EXACT SAME problem.

**Comment by b0urgeoisie** [comment]
well i submitted an issue at the very least

https://github.com/CleverRaven/Cataclysm-DDA/issues/48324

**Comment by chaosvolt** [comment]
Welp, good luck. When I get the chance I'll implement the workaround, as I'm willing to bet this issue will make it into 0.F given the timing of this.
