### ISSUE TITLE
Arcana basements are spawning without connecting stairs

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [chaosvolt/cdda-arcana-mod#18]
In a few worlds, the basements cannot be accessed without digging, in spite of an upstairs tile. Players are teleported upstairs through the floor if they try to ascend the stairs from the basement.

**Comment by chaosvolt** [comment]
Hnnng. The arcanist basements use the same mapgen ID as regular basements, I can't think of any JSON reason this is borking.

Are there ANY instances of vanilla basements doing this? If not, my guess here is that the hardcoded "generate some downstairs if house gets a basement" property is failing to consider mod content correctly.

You maybe should report this in the CDDA repo too, if you haven't already, and quote my second paragraph if you need it. Only problem is I don't recall if any official mods add any variants of actual basements (More Locations fake-basements don't count here), which doesn't bode well for this being solved before 0.D.

And just in case, pinging @Coolthulhu so they're aware of this, just in case.

**Comment by chaosvolt** [comment]
@BorkBorkGoesTheCode ?

**Comment by DanmakuDan** [comment]
Is forced stair alignment turned on in those cases? The placement will fail if there is a wall directly above the stairs.

**Comment by chaosvolt** [comment]
Wouldn't that kinda...be more likely to unfuck stair placement by forcing alignment?

**Comment by DanmakuDan** [comment]
The map generator will not bother placing the matching downstair when the aligned space on the floor above is a wall. While the code can offer to align stairways, all the map design that already exists would have to be updated as well in order to make use of the change.

**Comment by chaosvolt** [comment]
That's weird. @BorkBorkGoesTheCode get on here and tell us whether you had that option on. >.>

**Comment by BorkBorkGoesTheCode** [comment]
@chaosvolt stair alignment seems to be the most likely candidate.

**Comment by chaosvolt** [comment]
Ah, whee. Meanwhile it seems that @Noctifer-de-Mortem went and opened the issue instead: 

https://github.com/CleverRaven/Cataclysm-DDA/issues/22010

Go tell them what you know, whether you've found ANY non-mod basements affected by this, etc.

And on here, tell me whether messing with the layout of the arcansist basements can potentially fix it.

**Comment by Coolthulhu** [comment]
Forcing stairs to align isn't trivial. At the moment the game will simply give up as soon as a problem is encountered. There could be an "unwind and try again" code, but this wouldn't guarantee compatibility either, as a basement could be designed to be totally incompatible with house generation code.
When in doubt, try to have the stairs closer to the middle if possible. Say, if you've got a basement with an extra layer of rock on the opposite of stairs, move that layer to the other side, so that stairs are farther from the edge.

At the moment aligned stairs aren't mandatory, though. As long as all specials have aligned stairs, it should be fine.
There are examples of unaligned stairs in core game, most notably labs.

**Comment by chaosvolt** [comment]
Hmm. If that's the case and this is just stair-alignment being fucky, best to take things to any relevant issue in the repo, if any exists. I never ran into this because I generally never use that option, because it says up-front that it can break things.

On my end I'm going to see if I can scoot around the basements to make them less vulnerable to this. @BorkBorkGoesTheCode tell me if any of the 4 variants of arcanist basements have been especially prone to this relative to the others, if any.

And @Coolthulhu? Thank you.

**Comment by chaosvolt** [comment]
Yeah I started fiddling with testing this and basements in general are fucked with this setting enabled, almost immediately.
