### ISSUE TITLE
Allow human blood to be used in blood essence recipe.

### ISSUE THREAD

**Issue by ifffrt** [chaosvolt/cdda-arcana-mod#183]
I just found out that you can't use the human blood harvested from the gozu I just butchered in making blood essence, as well as the demihuman blood I got from a blank body. I'm not sure if this is intended or not, but imo I think human blood should be usable as ingredient in making blood essence.

**Comment by chaosvolt** [comment]
The main reasons I went with meat instead of blood, which I used to allow back in the old days, were:
1. Unless they changed it recently, there's no real mechanical way to distinguish between human blood and zombie blood, because they all used the same item ID.
2. You could extract absurd amounts of blood from basically any creature using a blood draw kit.
3. The penalty for drawing your own blood is basically a slap on the wrist, even less so than the older method of encouraging the player to make themselves bleed so they can create blood-soaked rags.

In order to balance it I'd have to either add some ADDITIONAL cost, or else make it take a lot of blood. See also the alternative recipe for blood essence, that does allow using blood but also adds some extra cost in materials and energy: https://github.com/chaosvolt/cdda-arcana-mod/blob/master/Arcana_BN/recipes/recipe_ammo.json#L73

**Comment by ifffrt** [comment]
But that's the recipe I used! Blood + quicklime + salt = blood essence. I just thought it was very inconvenient to have to kill animals that can be left to reproduce, while the supernatural creatures from another dimension couldn't be despite being powerful enough lore-wise to drop essence on death. And since quicklime is the limiting factor I just wanted to find some use for all the human blood I just extracted.

Also. I don't know if this means what I think you were talking about, but on the spawn menu the various types of blood all have different names. "Human blood" is just "blood", while "blood" from an animal's id is "animal_blood", and "tainted blood" is "blood_tainted" and "demihuman blood" is blood_demihuman". So I think that they might have already added a way to distinguish between the different types of blood?

**Comment by chaosvolt** [comment]
>Also. I don't know if this means what I think you were talking about, but on the spawn menu the various types of blood all have different names. "Human blood" is just "blood", while "blood" from an animal's id is "animal_blood", and "tainted blood" is "blood_tainted" and "demihuman blood" is blood_demihuman". So I think that they might have already added a way to distinguish between the different types of blood?

Ah, I'll have to look into whether that's standard in vanilla or still specific to Magiclysm. They added a crude hack for getting blood out of butchery for their weird blood-fueled CBM, I'd need to see if the feature has been set to be usable in vanilla. At bare minimum I can enable other types of blood to use for the alchemical recipe if so.

As for the "kill animals/people and harvest their flesh vs hunting weird monsters" bit, main lore reason is that producing blood essence is mainly rooted in producing energy from the life force of earthly creatures (also why anomalous zombies are more inclined to drop blood essence instead of normal essence), while most creatures that drop normal essence on death are implied to do this specifically because they're extradimensional. Balance-wise, it also incentivizes explicitly hunting for exotic monsters over farming more mundane creatures, which tends to lead the player to locations that spawn arcanist books and other weird stuff as a side effect.

The odd ones out are freaky mutant creatures, I need to remember to make sure those drop blood essence instead of normal essence. Some of the freaky mutant creatures, the ones the outdated CDDA wiki calls Unearthed, are probably also an edge case where it's not clear whether they should count as mutant monsters from this world, or extradimensional critters.

But yeah, if you meant specifically that the alchemical recipe should be allowed to use other types of blood, I'll look to see if that's doable in vanilla now.

**Comment by chaosvolt** [comment]
https://github.com/chaosvolt/cdda-arcana-mod/commit/44f061c61fe5aa534972b61911732ebaec518a37 should tackle this, but wanted to make sure that was specifically what you had in mind before I closed this.

**Comment by ifffrt** [comment]
Sounds like just what I wanted. But I noticed that in the older version it says "blood". Which is weird because in that case it should have shown human blood as an ingredient instead of just "blood" which is animal_blood. But I'll close it anyway.

**Comment by chaosvolt** [comment]
My guess is when they changed blood to have multiple sorts of blood, they presumably renamed the old blood item to human blood, since it's the item you specifically get when you draw from yourself.

**Comment by ifffrt** [comment]
Yeah, but in that case the screen should have shown "human blood" while I tested it. But it just showed "blood" (which is the "animal_blood" type of blood) instead of straight up saying human blood. But that sounds like one of those tiny and insignificant programming mysteries that will haunt us until the day we die.
