### ISSUE TITLE
Invalid effect, ID: arcana_clairvoyance_plus

### ISSUE THREAD

**Issue by SkitariiAuxiliary** [chaosvolt/cdda-arcana-mod#221]
I get the following Invalid effect error when trying to use the Eternity seal: Clairvoyance, using the latest DDA Arcana version at time of writing on the DDA experimental branch.

DEBUG: Invalid effect, ID: arcana_clairvoyance_plus
FUNCTION: void Creature::add_effect(const effect_source&, const efftype_id&, const time_duration&, bodypart_id, bool, int, bool, bool)
FILE: src/creature.cpp
LINE: 1347
VERSION: 6e07ff6

**Comment by chaosvolt** [comment]
Whoops, thanks for spotting that. That'd be a copy-paste error from when I overhauled magic seals to cast their own spells instead of being told to cast the relevant magic sign at the specified level (thus avoiding the magic sign exertion side effect).

I forgot that it's set up slightly differently in the BN version from the DDA one, the BN version uses a clairvoyance-granting effect while DDA version has to use a halo item that grants a mutation with the mutation flag, which is more clunky but relic clairvoyance in DDA was set up in a clunky manner.
