### ISSUE TITLE
can you make it compatible with generic guns reloaded_shot_00_arcana causes error

### ISSUE THREAD

**Issue by alp7292** [chaosvolt/cdda-arcana-mod#222]
can you make it compatible with generic guns reloaded_shot_00_arcana causes error

**Comment by alp7292** [comment]
can you make it compatible with generic guns reloaded_shot_00_arcana causes error

**Comment by chaosvolt** [comment]
I can look at it, but I highly doubt it. Generic Guns breaks a lot of content in ways that make it not play well with other mods.

**Comment by chaosvolt** [comment]
Can you at least post what error message it prints? That'd be a good start.

**Comment by chaosvolt** [comment]
First thing I see on looking into this is I suspect there may be some issue with Generic Guns overriding ammo types to define its own, which is just...why. I don't know if ammo types can be edited by self-copy-from or not admittedly, so not being able to edit the name makes sense as a reason for stuff like pistol and rifle rounds.

But if that's the problem, there was no reason to fuck with the shot ammotype because its name is ALREADY generic, since we don't have any distinction between 12 gauge, 20 gauge, etc.

**Comment by chaosvolt** [comment]
Ahah, I haven't been able to find any initial load errors but I do see this when I try to do the "retrieve reconnaissance case" mission:
![image](https://user-images.githubusercontent.com/11582235/148694824-f017524e-cd1b-4d84-baa0-9346a0bd931a.png)

This is because one of the bandits there is set to be armed with a shotgun loaded with purifying shot. Problem is, Generic Guns screws up and overrides the ammo type of all shotguns for some incredibly stupid reason.

Seeing as, even if I told it to load generic shotgun ammo, any mod that adds custom ammo like this is going to have that custom ammo be useless to the player, because it won't count as the ammotype that all shotguns have been edited to use.

I just tested and overriding vanilla ammotypes DOES seem to work now, in the old days it used to error if you tried. So this kinda thing works:
![image](https://user-images.githubusercontent.com/11582235/148695047-bd66edaa-c529-429e-86e2-f68d38ebb876.png)

So this is something that needs to be fixed on Generic Guns' end, because I can only keep Arcana from erroring in response to what's basically a Generic Guns problem, and the root problem here will still cause problems if you combine both mods until their ammo overhaul is fixed to not be so hacky.
