### ISSUE TITLE
Arcana does not support CDDA 0.F-3

### ISSUE THREAD

**Issue by PrecociouslyDigital** [chaosvolt/cdda-arcana-mod#223]
It seems like the fix for #201 didn't ever make it into the official 0.F release tag, causing the same error when run on 0.F-3

```
ERROR : src/main_menu.cpp:865 [bool main_menu::new_character_tab()] Error: item group "NC_JUNK_SHOPKEEP_misc" already defined with type "collection"
```

**Comment by chaosvolt** [comment]
Are you sure you're actually the 0.F version of Arcana? I get so many false positive reports caused by people using the incorrect version that it's hard to tell if there's an actual problem or if it's user error yet again.

Let me test this just in case, but at this point 0.F is so wildly, miserably far behind that it'd be better to either use current experimentals, or even better use Bright Nights.

**Comment by chaosvolt** [comment]
Okay yeah, far as I can tell it seems they presumably ported over a JSON-breaking change to the -3 version, because I'm 90% certain that this collection issue was NOT in the initial 0.F version, meaning my stable release should likely work with original 0.F but not 0.F-3. Figures.

I'll start work on making a new 0.F release I guess. That'll probably ensure 0.G gets released sooner too. XP

**Comment by chaosvolt** [comment]
There we go, this should work: https://github.com/chaosvolt/cdda-arcana-mod/releases/tag/0.F-3
