### ISSUE TITLE
Need a fix because of new mechanism of mutagens

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/cdda-arcana-mod#232]
See https://github.com/CleverRaven/Cataclysm-DDA/pull/55233
![image](https://user-images.githubusercontent.com/22638873/155917925-93858828-0969-4411-817c-3ec35ac91577.png)

**Comment by waveyl** [comment]
Same to cata++

**Comment by chaosvolt** [comment]
Oh FFS they would completely break instant mutagens...

**Comment by chaosvolt** [comment]
So I'm looking at this and I have some questions about @MylieDaniels' implementation:
1. Purifier working via hidden human mutations is pretty hacky, and I don't see any evidence that this plays nicely with the ability to set a mutation as unpurifiable.
2. Thresholds triggering when you have enough built up means you have no way to force a distinction between mutagen and serum, and worse there's no longer any good way to trigger a threshold check without it also building up a massive duration of mutagen.
3. There seems to be no way to control how rapidly mutation triggers anymore, nor any reliable way to affect how many mutations you'll get from one use of a mutagenic item? How do you get it to make a mutagen source reliably give you a single mutation or two, then immediately stop the effects?

Unless mutation spell effect finally has support for being able to cross thresholds, this seems like it's a very weird, inflexible system that's going to be a pain to update Arcana to work with.

**Comment by chaosvolt** [comment]
Looking into it, from what I can tell it seems I'd need to rig some new EOC stuff to call `u_mutate_category`, presumably with vitamins set to false...

**Comment by chaosvolt** [comment]
So I just tested a quick conversion to the new system, it doesn't work at all. No mutations. Tested vanilla alpha serum, also no mutations ever after waiting a full 24 hours.

**Comment by chaosvolt** [comment]
Okay, https://github.com/chaosvolt/cdda-arcana-mod/commit/3d5475fb2240eb006a2bcf756b4f14fed482f6fc now gets Dragonblood and PoTV to be as functional as vanilla mutagen and serums seem to be, and fixes load errors. Problem is, mutagen does absolutely fuck-all even after a week of waiting after loading up on the effect.

I'm gonna want to write up some EOC stuff to see if I can work around this nonsense and not rely on this current mechanic, so that vanilla DDA's broken mutagen system won't have adverse effects on Arcana's content.

**Comment by waveyl** [comment]
> So I just tested a quick conversion to the new system, it doesn't work at all. No mutations. Tested vanilla alpha serum, also no mutations ever after waiting a full 24 hours.
> 
> Injected 3 doses of alpha primer and waited 24 hours, no mutations at all. The mechanic seems to not be functional at all, in the "this was not even playtested" sense.

Alpha mutagen provide "mutagen" and "mutagen_alpha" nutrient, and alpha mutagenic primer only provide "mutagen_alpha" nutrient, so if you 'e'at some alpha mutagen, you can get mutations.

**Comment by MylieDaniels** [comment]
> 1. Purifier working via hidden human mutations is pretty hacky, and I don't see any evidence that this plays nicely with the ability to set a mutation as unpurifiable.
> 2. Thresholds triggering when you have enough built up means you have no way to force a distinction between mutagen and serum, and worse there's no longer any good way to trigger a threshold check without it also building up a massive duration of mutagen.
> 3. There seems to be no way to control how rapidly mutation triggers anymore, nor any reliable way to affect how many mutations you'll get from one use of a mutagenic item? How do you get it to make a mutagen source reliably give you a single mutation or two, then immediately stop the effects?

1.  I'm taking this with a grain of salt, as it does play nicely and you're the first person, including the entire dev team who reviewed it, to consider it hacky.
2.  Mostly correct, and this is intentional.  If you want to strictly trigger a threshold check, use the function Character::test_crossing_threshold.
3.  You can write your own EOCs, and you can precisely specify the vitamin amounts of an item.

I apologize for any inconvenience, but stress the fact that you are attempting to maintain out-of-repo mods for the Experimental branch of a rapidly updating game.  If these mods were in-repo, I would have updated them as I did every other mod that relies on mutations.

**Comment by MylieDaniels** [comment]
> So I just tested a quick conversion to the new system, it doesn't work at all. No mutations. Tested vanilla alpha serum, also no mutations ever after waiting a full 24 hours.
> 
> Injected 3 doses of alpha primer and waited 24 hours, no mutations at all. The mechanic seems to not be functional at all, in the "this was not even playtested" sense.

I suggest reading the pull request you linked and/or the ingame descriptions and log messages that will guide you down the path you need to take to mutate now.

**Comment by chaosvolt** [comment]
That is an odd system, serum being basically purely support rather than concentrated mutagen, but can see the logic behind it even if it does seem like it'd be counter-intuitive to returning players (as seen where I failed to realize that serum being unable to trigger mutations was intentional, since it's a complete 180 from previous behavior). I'll see if I can look into this further now that it's not late in the evening. I'll probably still want to shift towards experimenting in EOC when I get the time and energy to.

> I'm taking this with a grain of salt, as it does play nicely and you're the first person, including the entire dev team who reviewed it, to consider it hacky.

Hidden human mutations are definitely an extremely weird way to implement purifier. I suppose calling it hacky is a bit harsh, but it does strike me as a downgrade from the previous ability to remove mutations.

Important question I still can't figure out though: does this break the previous ability to flag a mutation as being unpurifable? Because normally if you mutate towards a trait that will cancel an unpurifable mutation, it will cancel it anyway, because unpurifable status only affected attempts to outright remove it with purifer.

**Comment by chaosvolt** [comment]
Related, mutating towards "human" likely also has the issue that purifer will also delete traits purchased in chargen, right? Unless human mutation has some sort of hardcoded exception baked into the code, but I didn't see any when skimming through the PR's file changes.

Removing chargen traits instead of trying to return to your start-of-game state seems like it'd be a serious detriment that'd strongly dissuade players from dabbling in mutations, because there would no longer be any way to return to their baseline state if they terminally mutate an unworkable combination of mutations.

**Comment by MylieDaniels** [comment]
In the past, unpurifiable only affected attempts to remove via purifier, but after this change, unpurifiable mutations cannot be cancelled.

The reason hidden human mutations are the new implementation is because purifier is not intended to wipe the slate clean.  It is not intended to be a free ticket out of a difficult situation, but rather a difficult choice.

Non-human traits from chargen can be cancelled by other mutations, and this is intentional.  Their immunity to cancellation from mutations was removed previously, and this remains consistent.

**Comment by chaosvolt** [comment]
> In the past, unpurifiable only affected attempts to remove via purifier, but after this change, unpurifiable mutations cannot be cancelled.

Ooh, that seems like something I can make use of to further enforce Dragonblood and PoTV being mutually-exclusive, and it would fix the weird way mutagen interactions frequently played havoc with Dragonblood's mutation chains.

The other purifier behavior still seems...odd, but I'll have to see if I can play around with EOC stuff. How does `u_mutate_category` work in this case? Suppose one were to write an EOC that goes "if has effect X, mutate category Y once or twice, then immediately remove effect X" for example. You also mentioned `Character::test_crossing_threshold` but that's a hardcode function, I don't see any way to get `u_mutate_category` to trigger threshold checks?

**Comment by MylieDaniels** [comment]
Ah, you're right, it is hardcoded, I'll add a way to call it from an EOC.

`{ "u_mutate_category" : "ALPHA", "use_vitamins": false }` is an EOC effect that would mutate a single mutation in the ALPHA tree one time (Currently there is not support in EOCs for calling something variable times except through kinda odd work-arounds, but I can work to add that).  Testing for status effects can be done in an EOC condition with `{ "u_has_effect" : "EFFECT_ID" }` , and taken away in an EOC effect with `{ "u_lose_effect" : "EFFECT_ID" }`

To do what you described:

```
  {
    "type": "effect_on_condition",
    "id": "example_gastropod_mutation",
    "condition": { "u_has_effect" : "EFFECT_ID" },
    "effect": [
      { "u_mutate_category" : "GASTROPOD", "use_vitamins": false },
      { "u_lose_effect" : "EFFECT_ID" }
    ]
  }
  ```

**Comment by chaosvolt** [comment]
> Ah, you're right, it is hardcoded, I'll add a way to call it from an EOC.

Hope that goes well, thank you very much. Hopefully later today I'll start testing out the JSON example provided.

Another option that may be worth exploring, depending on what you feel can be done with it in vanilla DDA and which would be easier: the `mutate` spell effect has support for immediately grabbing a specific category to mutate into, it would probably be very easy to also add support for a spell flag that, if present, tells mutate spells to also ping the the threshold check function.

I talked to Coolthulhu about the suggestion on the BN discord and he said it might have a use in BN too, and looking at the C++ for mutate spells it looks like the sort of thing I might be able to throw out as a PR for BN, if I get the chance sometime today.

One possible use both BN and DDA might have for it, Magiclysm might logically prefer having its Manatouched serum work instantly via a mutagenic spell, and it might get implemented that way in BN too, even though serum is still instant-effect for now (BN has implemented gradual mutations for some non-category stuff if I recall).

**Comment by chaosvolt** [comment]
Closing for now since mutagenic content in Arcana now works under the current system and the load errors should all be fixed, I might open up a separate issue as a to-do entry in case stuff comes up today and gets me sidetracked.

Also sent Noct a PR to update mutagenic stuff in Cata++

**Comment by chaosvolt** [comment]
> Ah, you're right, it is hardcoded, I'll add a way to call it from an EOC.

@MylieDaniels finally giving this a test to first fix some issues with Cata++, any way to trigger threshold tests via EOC yet?
