### ISSUE TITLE
Several errors on new experimental. 

### ISSUE THREAD

**Issue by zakhad** [chaosvolt/cdda-arcana-mod#237]
![image](https://user-images.githubusercontent.com/5264667/157405258-dca6242b-715d-4634-ac44-b310d6783a0b.png)
![image](https://user-images.githubusercontent.com/5264667/157405644-75b41ee9-9524-4b49-8ca6-9453763ef4e7.png)
![image](https://user-images.githubusercontent.com/5264667/157405714-a211753d-2864-4fde-bae2-8297ac97ce56.png)
![image](https://user-images.githubusercontent.com/5264667/157405778-5e831860-0dcf-4490-b458-66e9974feb7b.png)

![image](https://user-images.githubusercontent.com/5264667/157405451-2ff43468-86d3-42a8-98e9-9ed50d9d316c.png)

**Comment by chaosvolt** [comment]
You just grabbed an outdated version of Arcana, most likely one of the stable releases:
1. The old `offering` side effect was obsoleted and deleted quite some time ago, and `resist_effect` was updated to `resist_effects` back in december 2020.
2. The restored ritual blade no longer has an active verion (`veilblade_on`), that's also outright been deleted by now.
3. Third error makes me suspect that you need to delete the old mod folder entirely because it suggests that some failure to cleanup mods on update is going on here.
4. Healing items go reworked back during the bleed update.
