### ISSUE TITLE
"Frozen" bones can't be used earth talisman?

### ISSUE THREAD

**Issue by zakhad** [chaosvolt/cdda-arcana-mod#238]
![image](https://user-images.githubusercontent.com/5264667/157637832-a5ca7205-b3e6-446c-b02a-f4fd115dbd9e.png)

I'm able to use bones in their "frozen" state to make other recipes just not earth talismans

i.e 

![image](https://user-images.githubusercontent.com/5264667/157638227-01b5f1ec-66c2-4b1b-a742-ba76a7479e4d.png)

**Comment by chaosvolt** [comment]
Crap. Likely because earth talisman is technically a comestible. Out of the four talismans if I recall it's the only one that doesn't need to be a comestible since its use action normally removes the item on use anyway, but this is going to fuck with the flame talisman too since it can use various edible plants.

And of course I don't see a recipe flag for allowing frozen ingredients, the logic's hardcoded and looks solely for whether the components (not the result, that'd be actually useful) are edible while frozen, or whether tools include a hotplate or atomic coffee maker.

I can "fix" this for earth talismans technically since it's the only one of the four that can actually be a tool or generic without breaking something, water talismans avoid this since none of their components freeze, and air talisman could MAYBE be set to require fire (but even then it can't use the same fire-only recipe requirement other arcana recipes use because only a hotplate FFS), but of course flame talismans will be fucked over, because the entire point with them is a way of making fire.

**Comment by zakhad** [comment]
Can't you just use a crafting trick, by making bones into something, and that something into what is required for earth talisman? rather than directly crafting from the raw ingredient?

**Comment by chaosvolt** [comment]
That'd be hacky as fuck, to be honest. I'll convert earth talismans to a tool orr such since that should fix it, since like I said it's the only one of the four that doesn't actually need to be a comestible.
