### ISSUE TITLE
error code when playing this mod

### ISSUE THREAD

**Issue by fire78** [chaosvolt/cdda-arcana-mod#249]
![2022-04-07](https://user-images.githubusercontent.com/73866728/162358125-51202ec3-f206-48b8-98a2-b61cdcad51ec.png)

**Comment by chaosvolt** [comment]
That's for desolate barns. Update Arcana, reminder that launchers generally aren't the best way to update third-party mods, and to always get active mods from source repos rather than compliations. This was fixed by: https://github.com/chaosvolt/cdda-arcana-mod/commit/f8ba62c5dc35196ada2750f704a136fdddec9b17
