### ISSUE TITLE
Balancing suggestion: move Rift Focus Projector CBM slot to right arm

### ISSUE THREAD

**Issue by YuPro** [chaosvolt/cdda-arcana-mod#251]
**Justification:**
- Combat CBMs tend to be in right hand, which is logical because characters are right handed «by default». It helps with not over-weaponising CBMs and force to choose. Also it helps a little bit with utility CBMs, for example: Arcana Purifier start have 5/5 slots in hand_l, multitool, fingrerhack and lockpick, it effectively lock you out of installing rift while still allow to install every other combat CBM (that is not full body). 
- Laser finger, which is part of recipe is in right hand.

**Alternative:**
- It's possible to make another CBM that would be "Rift Focus Projector (R)" which can be crafted in 1 minute with some tools and skills from original rift projector. Changing CBM side would be actually logical feature in game but while it's not here it's possible to make "better CBM system" with workaround like that.
 
Also I have question: are straightforward higher stats on Arcana CBMs intended?
It may be not so pronounced with "Rift Focus Projector" but "Electrothermal Arc Projector" don't take space in torso (16(!) torso slots for "Chain Lightning" which is part of recipe) and quite higher damage. It's heat damage, not electric, maybe latter is that much better to justify x2 damage and range, I'm not knowing enough about mechanics to be sure.

Or the reason is that you think vanilla CBMs are too weak to even install them and trying to make them viable?

**Comment by chaosvolt** [comment]
Ah yeah, I'd changed the Rife Focus Projector's slot selection to the left hand in https://github.com/chaosvolt/cdda-arcana-mod/commit/554f0d28906709de69875c80ab8e963e46d87d20 thinking it'd reduce competition with other CBMs, didn't realize that the left hand would be that much more overloaded as it is.

As for slot usage overall, the idea was mostly just to try and make them less restrictive overall mostly because the bionic slots are hard to juggle, and given the effort it usually takes to obtain the magitech CBMs, it seemed acceptable to make them more accessible to a character who by that point is likely already a late-game cyborg given the expected point where you'd have reliable access to the Arcana CBMs.

That said, swapping back to right hand for the ranged attack bionics should be alright, and could re-add any missing cases of torso slots if it really seems worth re-adding since the torso has a lot more space than the hands.

**Comment by YuPro** [comment]
Will do. Also I want to propose some changes to melee weapons to made them work with vanilla martial arts.

I looked at martial arts json and there you did add every weapon manually. Not sure if it's legacy but there are 2 issues:
- As I understand, weapons works with martial arts through "weapon_category" now. So I believe "copy_from" in weapon json and direct mention of weapon in martialarts are redundant. I'll add "copy_from" to incorruptible sword (arming sword) and restored sword (zweihander, like for corrupted). To corrupted_on I'll add "weapon_category" because of your comment that you can't use "copy_from" there. That will allow use them with vanilla styles like medieval swordsmanship and will be patch-proof. Also - do you think it's better to delete "POLEARMS" from luminous hammer or it's ok that it's compatible with Sōjutsu?
- Do you think it's worth exploring if weapon categories are ok with Via Gladium et Malleo requirements and change json to work with that categories?

**Comment by YuPro** [comment]
Also about greatswords - you did delete "ALWAYS_TWOHAND" from cursed sword and restored sword is without it either. Can I ask why are you using "zweihander" and not "longsword" then?

**Comment by YuPro** [comment]
Ok, I do understand now that at least some of this decisions are linked to absence in BN and maybe in stable, can't check latter now.
So, is it bad to add "weapon_category" dependencies in this case?

I can make pull request already and you'll see what changes I mean. But without changes for example luminous hammer will work with silat and sōjutsu.

**Comment by chaosvolt** [comment]
> Do you think it's worth exploring if weapon categories are ok with Via Gladium et Malleo requirements and change json to work with that categories?

Last I checked, you can still add weapons to a martial art explicitly, and this is needed for styles where the weapon list needs to be explicit. Look at the comment for Via Gladium et Malleo in particular and you'll see that the weapon requirements are rather strict, categories aren't going to cut it.

> Also about greatswords - you did delete "ALWAYS_TWOHAND" from cursed sword and restored sword is without it either. Can I ask why are you using "zweihander" and not "longsword" then?

In terms of size it's meant to be in between a longsword and a zweihander, so it could use either. It used to be much closer to a zweihander outright, and that's why it's set to look like a zweihander.

> Ok, I do understand now that at least some of this decisions are linked to absence of "weapon_category" in BN and in stable.
So, is it bad to add that kind of dependencies in this case?

BN lacks them, yeah. It's on the list of features to eventually port over though.

> But without changes for example luminous hammer will work with silat and sōjutsu on experimental.

Uh, well is the vanilla lucerne hammer usable in those styles too, or not?

**Comment by chaosvolt** [comment]
Looked at the PR and it seems alright, gonna grab latest build to test some things, then update version and I'm guessing that probably resolves the issue?

**Comment by YuPro** [comment]
It's just if martial style will be bound to weapon category in addition to explicit weapons expanding of the list would be automatic when new songs are added even if they're added by another mods. But I heard you - categories are too broad, well, to bad.

As for Lucerne hammer - yeah, it's polearm and works with these styles, my question was more about that luminous is "one-handed upgrade" so I wasn't sure if it must work lore-wise.

Issue can be closed.

**Comment by chaosvolt** [comment]
True, it can go either way I guess. In that case seems to be fine then. Gotta update it with some sort of JSON chance to mutations it looks like.
