### ISSUE TITLE
Monster drops not working

### ISSUE THREAD

**Issue by Roet718** [chaosvolt/cdda-arcana-mod#259]
In my new experimental dda world I noticed that I was having a lot of trouble progressing in arcana because I was getting almost no drops. After killing 1976 monsters I accumulated 3 essence, no blood essence and 1 amorphous amber. I suspect it might be a mod conflict but I'm not sure which.
[mods.zip](https://github.com/chaosvolt/cdda-arcana-mod/files/8835593/mods.zip)
.

**Comment by chaosvolt** [comment]
What monsters have you been hunting? Generally you want to go after nether monsters, the more abnormal zombies, mutants, triffids, blobs, fungal monsters, etc.

Also are you playing with item spawn rate below 1.0x? It does affect monster drops if I recall.

**Comment by Roet718** [comment]
I havent been hunting too many nether creatures, I would say a third of that 2k is bl9 and the rest is city clearing. But I know from previous games and from looking at the monster drops file that many city monsters have a low to medium chance to drop arcana items as well which with this volume of kills would have made probably 100 times more drops in my previous games. Im using default settings for spawn rates.

**Comment by chaosvolt** [comment]
That's weird, hmm. A screenshot of the kills screen might help I guess. I don't think any of the other mods in the mod list should interfere with Arcana but not sure.

**Comment by Roet718** [comment]
Sure
![kill1](https://user-images.githubusercontent.com/19896899/171958427-a780781b-8c5f-4ec6-b9cf-8d426da9a1ad.PNG)
![kill2](https://user-images.githubusercontent.com/19896899/171958429-298d71b0-606e-4c8d-8f33-d50700e7e1ac.PNG)
.

**Comment by chaosvolt** [comment]
Let's see...looks like BL9 monsters predominate, as do a lot of assorted zombies, only some of which are particularly anomalous. The necros, dementias, and shady zombies should've been at least somewhat noticlbe spikes of various arcana items.

Are the wasp variants new to DDA, or added by a mod? Wasps are also a case where you have a tiny chance of getting a barbed stinger. I could also see about adding monsterdrops to feral humans, in the same vein as survivor zombies.

**Comment by Roet718** [comment]
Shadow crawlers are bl9.

**Comment by chaosvolt** [comment]
Seems like I should look into adding a patchmod for that someday, hmm.

**Comment by Roet718** [comment]
I guess it could just be the world stage isn't at the point the more evolved zombies are showing up. but still it feels really low

**Comment by Roet718** [comment]
I dont know about the wasps seems vanilla though.

**Comment by chaosvolt** [comment]
Yeah, the relative amount of more anomalous monsters on there does seem to lean towards unevolved stuff that likewise makes up a fairly small proportion of the killcount, so that could be it. It doesn't help that RNG is always kinda finicky when the amounts are low enough. I'll want to give the monster drop rates a once-over and maybe see if there's any obvious inclusions I can add that might help improve things, but it's definitely hard to tell how much of it is just bad RNG vs. a potential problem.

I'd been meaning to maybe in the future tinker with some ideas that'd help give certain things like monsterparts some solid, reliable spawns associated with more anomalous locations, but that still hinges on finding good places to inject spawns of Arcana content into without being too disruptive.

**Comment by Roet718** [comment]
alright thanks for the fast response and keep up the great work :) i guess ill just keep playing and see if it picks up. Oh one suggestion I had was adding the allowed_items allows_tail and allows_talons tags for the dragonblood mutations so that vanilla items which allow those will work without being xl. Oh and maybe adding compatibility for magiclysm dragon scales and hide and demon chitin to the druid staff as those would be organic, not sure if anomalous tho.

**Comment by chaosvolt** [comment]
Ah, nice. I hadn't been following development of DDA too closely so that seems like a handy feature to make use of, maybe even worth porting over to BN sometime. And thanks, I'll tinker with some things when I get time. Good timing as had basiclaly just gotten home not long after the issue was opened.

**Comment by Roet718** [comment]
Awesome thanks! closing this now.

**Comment by chaosvolt** [comment]
Bit belatedly, I'm hoping https://github.com/chaosvolt/cdda-arcana-mod/commit/546b88e6fd97ab7adc136348a1da873529884914 will help with it a bit, but still have yet to investigate if any of the relevant mods interact with Arcana to potentially cause this.

**Comment by Roet718** [comment]
awesome ill update it and try it out! thanks.

**Comment by Roet718** [comment]
Oh just wanted to add i cleared an arcana house with dementias and
received a lot of essence so those drops are clearly working. The lower
drops might also have been due to a vanilla bug ive noticed where
autopickup doesn't work on items with the zero_weight flag.
