### ISSUE TITLE
Bit of Feedback

### ISSUE THREAD

**Issue by nukularpower** [chaosvolt/cdda-arcana-mod#263]
Hello, not sure where else to leave feedback for the mod, so feel free to delete this if inappropes.   But had a couple thoughts to share after playing with the mod for some time:

1)  Seal:  Confuse Monster is stupidly overpowered.   I want effective magic but this should just be renamed "god mode", because thats what it is.   It makes killing swarms of high level undead pathetically easy, along with anything else, from dracoliches in the ruins to any other monster I've seen in many runs.   The AOE range is huge and nothing seems to resist it - everything becomes target dummies for a SUPER long duration, and if more enemies show up, you can just cast it again.

On top of all that, it's a stupidly effective escape tool - you can just cast it and walk away if you don't feel like mowing down a bunch of derpy target dummies.  Heck, it doesnt even cost mana, just a bit of stamina, there is no failure rate, and you can use it with any weapon in hand.  

The name is "confuse monster",  singular - not "confuse monsters", plural.  It really seems to me like this spell should match the name and only affect 1 enemy at a time, rather than everything on the screen at once, and even then it's probably still too good.

2)  I took the dragon mutation line and I understand that there are hunger and thirst penalties, but the levels currently seem out of line.  I go to sleep Turgid and then die in my sleep from dehydration, just in a normal rest.  I need gallons of water - it's practically impossible to do anything but boil water and drink.    It feels like it should be toned down at least some.

Other than that, I love the mod, and appreciate your work making it.   Way better than Magiclysm imo :)

**Comment by chaosvolt** [comment]
> Seal: Confuse Monster is stupidly overpowered. I want effective magic but this should just be renamed "god mode", because thats what it is. It makes killing swarms of high level undead pathetically easy, along with anything else, from dracoliches in the ruins to any other monster I've seen in many runs. The AOE range is huge and nothing seems to resist it - everything becomes target dummies for a SUPER long duration, and if more enemies show up, you can just cast it again.

It'd be nice if monsters had some way to define resistances to status effects. Some options I could do for this would be to both add the stun immunity flag to more of Arcana's bosses and rebalance the duration to be shorter. Right now if I recall its duration is balanced as a debuff (see https://github.com/chaosvolt/cdda-arcana-mod/blob/master/GAME_BALANCE.md) but it could be nerfed to scale the same as DoT and paralysis durations.

> Heck, it doesnt even cost mana, just a bit of stamina, there is no failure rate, and you can use it with any weapon in hand.

They do drain your fatigue as well. Sadly failure rate can't be used at all for spells in Arcana since casting EXP is based off spell difficulty, mandating the `NO_FAIL` flag. Likewise, `NO_HANDS` flag is used because:
1. The way casting costs escalate with hand encumbrance without the flag is very badly balanced.
2. There's no way to designate faction-specific magic focuses. Ideally Magic Signs should be usable with weapons that suit the faction using them, but otherwise require empty hands, but not an option sadly.

Not many things I can do about that unless I mess with the spell rank to beef up the overall costs.

> I go to sleep Turgid and then die in my sleep from dehydration, just in a normal rest.

If this is true and not exaggeration, that sounds like a bug. At least I hope it's a bug, if you're playing on DDA for all I know they could've messed with thirst calculations in some way I haven't been made aware of.

Could it be you've been spamming Sanguine Mark spells before going to bed? Keep in mind that, like with Magic Signs and fatigue, Sanguine Marks add extra hunger and thirst drain to offset how spammable they can be if you have any source of life-drain or self-heal.

> It feels like it should be toned down at least some.

That said, I'm very tempted to tone down the thirst multipliers to about half that of the hunger multipliers anyway, since thirst management is mostly just tedium than actual resource management, making it underwhelming as a drawback. Food procurement requires actually going out to do something at least once (even if it's just to gather seeds for farming), water management much less so.

In any case, thanks. I can see what all I can mess with when I get the chance.

**Comment by nukularpower** [comment]
Hey,

Thanks for the reply.  I was not exaggerating about the death-in-sleep thing, though as it turned out, I also had the flu and a debuff from using the silver athame that I think also causes hunger/thirst.    Even so, I do still feel it's a lot without that stuff.

In regards to confuse, there is just no downside at all - my character is chronically overburdened and slow as hell due to my pack rat nature but I can easily kill a whole crowd in one cast thanks to the extremely long duration (around 2 minutes gametime, iirc.)   Like I said, I'd personally like to see it be single target, but it's way too good as it is - from the toughest mobs to the easiest, it feels like a waste of time to cast/use anything else.  There are similar spells in Magiclysm (Ionization) but it is way shorter duration, requires a magic catalyst, costs mana, has a high failure rate, etc.   Confuse just outclasses everything else from either mod.

Thanks again

**Comment by nukularpower** [comment]
Can I ask a question here?   Mark:  Revenant Blood states that it "protects against pestilence in food and water."   Does that mean you can drink unclean water and be okay?   If I misinterpreted that, that explains the flu, haha..

**Comment by chaosvolt** [comment]
It should protect you against food poisoning yeah. Flu just happens at random if your healthiness is low, so drinking bad water won't cause that.

**Comment by chaosvolt** [comment]
So, finally got some chance to look into a bit of the feedback and make a couple tweaks. For starters, made thirst tick half as frequently as hunger for the athame's side effect. Also halved the extra penalties to thirst Dragonblood mutations get, so that should be less of a problem compared to food. On looking at it I realized I was wrong actually about Draconic Exertion, it actually only increments hunger, I'd forgot and thought it also affected thirst.

For Confuse Monster, I feel that fixing this will be a bit more complex than I first thought. One improvement I could make is making it a much smaller AoE, possibly making giving it range so you can place it elsewhere in exchange, but that only really makes it so you can't stunlock as many monsters at one time.

I think the more useful solution will be to nerf the overall balance of certain spell properties. Here's the table of Magic Sign balancing from the game balance file for example:

Property | At Minimum Level | At Max Level
--- | --- | ---
Energy Cost | 500 stamina * ( Spell Rank + 1 ) | 250 stamina * ( Spell Rank + 1 )
Spell Exertion | 50 sec * ( Spell Rank + 1 ) | 25 sec * ( Spell Rank + 1 )
Casting Time | 0.4 sec * ( Spell Rank + 1 ) | 0.2 sec * ( Spell Rank + 1 )
Total Damage | 20 per Spell Rank | 40 per Spell Rank
Duration, Protective Buffs | 2 min per Spell Rank | 4 min per Spell Rank
Duration, Other Buffs | 6 min per Spell Rank | 12 min per Spell Rank
Duration, Debuffs | 20 sec per Spell Rank | 40 sec per Spell Rank
Duration, DoT/Paralysis | 8 sec sec per Spell Rank | 16 sec per Spell Rank
Summoning Duration | 30 min per Spell Rank | 60 min per Spell Rank

Confuse Monster is balanced as a debuff, so that means 20-40 seconds of duration per "spell rank" (3 in this case, so a whopping 60-120 seconds duration). I feel that debuffs and DoT durations could definitely be made quite a bit lower. As far down as a minimum of 2 seconds per spell rank for DoT/paralysis effects (since Arcane Blessings start off half as effective, that means minimum for Magic Signs needs to be something still neatly divisible by 2).

Related, I'm likely going to also nerf summon durations at least a bit more, probably down to 20 minutes per spell rank at minimum level.

One additional that could be used regarding Confuse Monster: doing what I do for spell damage and split the duration into two spell effects, one having half effectiveness across the entire area, and a second doing out the other half in a much smaller area of effect, the whole "spike damage" thing I use to encourage the player to center attack spells on priority targets instead of just vaporizing a whole group for max damage.

**Comment by DamienRoyan** [comment]
> They do drain your fatigue as well. Sadly failure rate can't be used at all for spells in Arcana since casting EXP is based off spell difficulty, mandating the `NO_FAIL` flag. Likewise, `NO_HANDS` flag is used because:
> 
>     1. The way casting costs escalate with hand encumbrance without the flag is very badly balanced.
> 
>     2. There's no way to designate faction-specific magic focuses. Ideally Magic Signs should be usable with weapons that suit the faction using them, but otherwise require empty hands, but not an option sadly.


Regarding the no hands bit, I'd like to imagine they are similar to Dragon Shouts from Skyrim since you simply speak them :D

**Comment by chaosvolt** [comment]
Seems like a workablw reason too, heh. And oh right, I'd gotten distracted so had forgot about the issue, I should check to ensure I didn't miss anything.

**Comment by nukularpower** [comment]
A smaller AOE would definitely make sense.  And/or higher fatigue usage maybe?

Otherwise that all sounds great, thanks for taking the time to listen.   Just a random side question:  How come this isnt included in CDDA but Magiclysm is?  I find this mod vastly more immersive and fitting than the super-gamey Magiclysm.

Thanks for all your work

**Comment by chaosvolt** [comment]
The AoE for Confuse Monster got toned down a bit since then yeah. Not sure yet about fatigue adjustments though.

>  How come this isnt included in CDDA but Magiclysm is?

Back in the day it used to be, but as I'm not longer a contributor for DDA it got obsoleted and removed as no one else was maintaining it.

> When you've maxed out the dragon mutations from the heart, or the spells from the ritual blade, it would be nice to get some feedback about it, so you don't keep wasting stuff trying.

I think I might be able to implement that in the DDA version at least since it relies on EoC stuff to work around the new hacky mutation system. Won't be an option in BN version sadly.

**Comment by chaosvolt** [comment]
Should be hopefully done with this since the main points got tweaked, only thing left is seeing if I can implement that "hint that you've reached the end" idea at some point in the future, if I can find a way to do so in both versions.
