### ISSUE TITLE
Shrouded Exotic Amulet doesn't function (as intended?)

### ISSUE THREAD

**Issue by TheJazziestCat** [chaosvolt/cdda-arcana-mod#295]
I'm playing on a recent experimental version (fa069f8) and trying to make use of the shrouded exotic amulet: "Using it will... [render] you undetectable to the undead...." And it sort of works. Zombies' attitude towards me becomes "Ignoring." However, despite this, zombies still charge right towards me and attack. I'm at a bit of a loss as to what's going on.

**Comment by chaosvolt** [comment]
In a nutshell: it still allows them to hear and smell you, and they can still path towards your position due to that. This would normally be the same standard caveat that regular invisibility has, except the life sign suppression effect works via using `anger_relations` and `ignored_by`.

Both of these are supposed to make them non-hostile, not merely blind to you. So there's a code flaw here where it still interprets an attempt to move into your position as an attack for whatever reason, even if the offending monster is supposed to be outright non-hostile to the player at the moment.

I tried messing with scent overrides to see if I could make that work, but I ran into another flaw: even to this day, not all mutation properties work right when called from an enchantment. `anger_relations` and `ignored_by` both work from an enchantment, but `scent_intensity`, `scent_mask`, and `scent_type` don't, and if I recall neither does `noise_modifier`. That's basically just yet more bugs with relic and enchantment code.

So far, best I can do is try to update the description to warn players that they're only undetectable visually, unless I can find a way to fix that bug. And even then, I personally can only fix it in Bright Nights, you'd have to hope someone will notice and port it over to DDA.

**Comment by chaosvolt** [comment]
Updated item descriptions to at least clarify that, hoping in the future I'll figure out some way to rig it to actually prevent being heard or smelled by zeds.

**Comment by Dan1ss1mo** [comment]
> Updated item descriptions to at least clarify that, hoping in the future I'll figure out some way to rig it to actually prevent being heard or smelled by zeds.

smelled part shold be mostly covered now, as most zeds lost they're scent ability
