### ISSUE TITLE
Science Lab Loading Bay elevator is bugged

### ISSUE THREAD

**Issue by WreckingAbandon** [chaosvolt/cdda-arcana-mod#298]
Currently trying to finish another mission for a CF purifier guy and the lab I needed to retrieve some intel from has a bugged elevator. Examining the controls only gives you one option, the floor you are in. The elevator below is also bugged the same way when I teleported two floor down.

**Comment by chaosvolt** [comment]
Ah, looks like at some point they moved the contents of the microlab to level minus-2.

**Comment by chaosvolt** [comment]
Wait no, it's the same for `4x4_microlab_arcana` too. Is this in BN or DDA? Either way, test a vanilla microlab, does the elevator work there too? Because the microlab variant in Arcana only differs from the vanilla `4x4_microlab_surface` in that a single room in the bottom layer is replaced with the server room.

**Comment by chaosvolt** [comment]
Okay this doesn't make any fucking sense. Even replacing the variant entrance bunker with a vanilla one, it still doesn't want to work. :/
