### ISSUE TITLE
[Arcana x Aftershock]Can't put av-22 into holster

### ISSUE THREAD

**Issue by waveyl** [chaosvolt/cdda-arcana-mod#312]
V29 in Aftershock is replaced with av-22, so Arcane Purifier start with av-22 contained in holster, but v-22 is larger than v29, then
![image](https://user-images.githubusercontent.com/22638873/216749851-83c0d260-51fc-407c-ba08-f4d501572e97.png)

**Comment by chaosvolt** [comment]
Ah, the eternal saga of there always being something that screws up the purifier's laser pistol until it no longer fits in its current holster. This is like the third or fourth time that's happened so far, first one from a mod interaction though.

If I can't find a fitting laser weapon that doesn't get broken by any in-repo mods, I could possibly work around this by just giving that profession the Rift Focus or Electrothermal Arc CBM. Fits the same role since on-gamestart their only way to fuel the laser is through their UPS bionic.
