### ISSUE TITLE
[DDA] Crafting Proficiency Changes.

### ISSUE THREAD

**Issue by nemesis688** [chaosvolt/cdda-arcana-mod#322]
Here I go again pinging you about DDA experimental changes.

DDA has merged in some crafting proficiency changes.

Probably easier to just link the pull requests. The first link contains the documentation updates and a a python(?) script to handle the conversion.

Proficiencies: Fail multiplier -> skill penalty
https://github.com/CleverRaven/Cataclysm-DDA/pull/64079

and what seems to be the main pull going in to the overall idea behind the changes:

Rewrite crafting skill checks to use normal roll
https://github.com/CleverRaven/Cataclysm-DDA/pull/63886

Your More Survival Tools mod also trips the debug message for this. Also, Cata++; should I make a issue over there too? I know you are active in that mod so I'm not sure if it's needed or not.

**Comment by chaosvolt** [comment]
Ah, guess I'll have to mess with this to see what needs to be converted, hmm.

**Comment by chaosvolt** [comment]
That said, most of the copy-paste of proficiencies is from the days because the proficiencies themselves had default time and failure multipliers applied, so most examples of this would've just been specifying values that're now the default values anyway, so a lot of this will likely be just removing the now-redundant multipliers in the recipes for futureproofing.

**Comment by chaosvolt** [comment]
https://github.com/chaosvolt/cdda-arcana-mod/commit/7d375ec362298ce5eb39277d42a16ef2498e8345 should fix this, now I need to update over mods while I'm at it.

**Comment by chaosvolt** [comment]
That should be all relevant mods I think.
