### ISSUE TITLE
update mutations for cdda 

### ISSUE THREAD

**Issue by alp7292** [chaosvolt/cdda-arcana-mod#325]
can you update mutations for cdda pr #63974

**Comment by chaosvolt** [comment]
Ah, weird. I'm gonna hope this actually works right for Arcana's mutation categories, since we don't rely on the vanilla mutagen EoCs and mutagen vitamins due to how wonky their behavior is. Assuming it only affects the underlying "call chance to mutate and use the hardcoded functions to do so" behavior both vanilla and Arcana EoCs eventually reach in the end, it should work fine though.

**Comment by chaosvolt** [comment]
There we go. PoTV doesn't interact with any vanilla mutations and logically shouldn't have any need to override starting traits, while Dragonblood does so added that to it.

**Comment by alp7292** [comment]
thanks for your effort
