### ISSUE TITLE
Dragonblood threshold prevents other mutations

### ISSUE THREAD

**Issue by Dracque** [chaosvolt/cdda-arcana-mod#422]
Using mutagen or serums after getting the "Dragonblood" trait does not mutate the player but still shows the generic message and can inflict pain.

Versions and configuration
- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: fba1da1 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Arcana and Magic Items [Arcana],
    Disable NPC Needs [no_npc_food],
    Limit Fungal Growth [limit_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by chaosvolt** [comment]
Intentional, going post-thresh locks you into that mutation tree. So does Paragon of The Veil. I'm still torn on whether I want to keep it that way (a good reason in the case of Dragonblood is the mutation tree is VERY interconnected at the later stages and competes strongly with a lot of mutations, so a wayward mutation can potentially undo a huge chunk of what makes the mutation category playable in one swig), but it's not a bug per se.

**Comment by Dracque** [comment]
Understood. I wasn't entirely sure if this was intended or a bug.
If it's possible, having the description of the threshold mutation tell the player mutagens/serums won't work (or a message when trying to mutate using mutagen/serum).

Something that made me think it was a bug was the Oath of the Chalice NPC giving the quest to earn a blessing using the restored blade despite my character having crossed the Dragonblood threshold.

**Comment by chaosvolt** [comment]
Ah yeah, the dialogue should be cutting the quest chain early on noticing the player already has a threshold, odd. I'll have to look into that.

**Comment by Dracque** [comment]
If it helps, this issue can be closed and I'll open another one for the quest itself.
I've got some time and could try to replicate the NPC giving the quest when it shouldn't, maybe it'll make tracking down the problem easier.

**Comment by chaosvolt** [comment]
Ah, aight. Good luck, and thanks.
