### ISSUE TITLE
Feature request: Arcane profession

### ISSUE THREAD

**Issue by Maddremor** [chaosvolt/cdda-arcana-mod#45]
I'm pretty hyped for the urban awakening stuff in the pipes, but I think there is some modes of play that are unfilled. 

I propose a proffesion that starts with with no skills, no valuable gear (not naked though) but with a collection of arcane books. The idea is then to study and develop your arcane powers, not loot the works of other mages. 

Name suggestion is "Found Lore". Items could be pants, light jacket, etc, a collection of powerful books and a swag bag to carry them.

**Comment by chaosvolt** [comment]
Hmm, might be interesting, hard as it is to add things that entail not looting other places, but starting with the books would be a nice touch. The apprentice profession is sorta this and was enabled for use in normal scenarios, but they're only in a state that allows breaking into the non-booklearned recipes. 

As for books though, I wonder which. History of Alchemy is a given as it's the go-to for building 1-3 skill, possibly The Six Pillars. I'm not sure about the faction books (Sanguine Codex, The Cleansing Flame, and Oaths To The Chalice) so that leaves only A Story In Shadow and To Master The Unknown.

A Story In Shadow started as a purely high-level book, and a very rare one due to implying it was written after all three factions established themselves then died out (i.e. post-cata, with the fact one can spawn in the oldest structure being a thing I'm still on the fence about), but as it's slowly gained a LOT of lower-level recipes, I have good reasons to maybe lower its minimum level.
