### ISSUE TITLE
Error on loading, bad terrain

### ISSUE THREAD

**Issue by Szara-ManOfHonor** [chaosvolt/cdda-arcana-mod#70]
I just updated everything to CDDA build 9092 and suddenly I'm getting spammed with errors. I've poked around, updated to the latest Arcana, and tried to troubleshoot, but to no avail. I get

`ERROR : src/savegame.cpp:858 [void overmap::unserialize(std::istream&)] Loaded bad ter! ter curious_structure_b`
For basically, if not actually, every terrain in the Arcana mod, and existing sites are replaced with a maptile of nothing. I can see the Arcana files defining them are clearly where they should be, and I still have the Arcana skill, so I know it is partially loading, but for some reason the terrain is fouled up, and I can't seem to figure out why.

Update: That was loading an existing game. I started a new world with just Arcana mod and it works. I need to look into this some more.
Update part 2, mechanical boogaloo: A new game with the same modset as the world that is causing me problems loads just fine, the shrines (that's what I've been checking since I know one is missing in my current game) exist as they should.
This is not making any damn sense.
Update part 3, return of the AAAHHHH: Well, I think I found it. In the old save the map locations were all like "shrine_anomaly". New games they're all "shrine_anomaly_east" or another cardinal direction. Other than vaguely assuming this is the result of some game update shenanigans I'm not going to pretend to try to know WHY this is. I'm just going to edit my map files and append _north on everything because screw it. Eventually. Because there are many errors like this in the debug log and I don't feel like bothering with it. Maybe I'll just play this world on the old version until I get bored enough to make a new game.

I'll leave this here for anyone else who has the same problem, maybe it will grant them a glimpse of sanity.

**Comment by chaosvolt** [comment]
Old save issue, yes. Reason here is that when I converted most of the locations from fixed, north-facing locations to places capable of rotating, this somehow breaks old saves and makes it freak out, as the pre-existing locations refer to overmap terrain IDs that no longer technically exist (as rotated versions plop cardinal direction into the ID automatically at the special level AND during saves, even though this is absent in the mapgen and overmap terrain entries).

The errors however should be safe to dismiss, and locations you've visited before should still be unaltered even though they now show as a "nothing" on the map. I've long since learned from my mistake and made sure to retain backups of old mapgens and overmap terrains when I did the same conversions for Noctifer in Cataclysm++.
