### ISSUE TITLE
Is the spell-stuff branch stable?

### ISSUE THREAD

**Issue by ImportTaste** [chaosvolt/cdda-arcana-mod#74]
Just curious, it looks like an improvement over the master branch.

**Comment by chaosvolt** [comment]
As of right now it's usuable but still incomplete and not yet fully tested. I've been meaning to run through some last steps prior to merging my current progress as a good "part one" but that list has gotten pretty long. Right now it's:
1. Convert relevant mutations to hand out their associated spells.
2. Split off spellcraft/chargen mutations from their Dragonblood versions.
3. Decide whether Summoner and Arcane Purifier get their spells via custom mutations now, or tie them to profession traits since they're going to eventually need dialogue checks that specify "Purifier vs. regular mage hunter" and "Summoner vs. regular arcanist" anyway.
4. Move no-longer-used magic sign items to obsolete.json.
5. Playtest all spells.

**Comment by ImportTaste** [comment]
Should I use use the master branch for now then? Or is the master branch in an awkward spot as well?

**Comment by chaosvolt** [comment]
Master is working fine, it just still uses the old hacky "spells derived from mutations plus items" system.

**Comment by chaosvolt** [comment]
And now, no longer relevant as I've merged part one, and will continue more work on it soooon.
