### ISSUE TITLE
Summon jugg is still in old format

### ISSUE THREAD

**Issue by adamkad1** [chaosvolt/cdda-arcana-mod#75]
its still useable from mutation menu instead of magic menu

**Comment by adamkad1** [comment]
same with rite of the beyond

**Comment by chaosvolt** [comment]
1. Summoning yuggs has been depreciated and moved to obsolete.json, will no longer be obtained by Dragonblood. I might rework it to act consistent with other spells, but otherwise my plan is limited to ensuring doesn't break anything if a character from an old save. I definitely need to at least make the mutation description allude to it being no longer used...
2. Rite of Blood and Rite of The Beyond are in a bit of a weird place at the moment, they probably could be turned into special spells that call `spawn_item` permanently, but even then I'm not 100% sure whether they should retain those abilities as they're in an odd place, thematically. Even then, their current handling (consuming hunger, thirst, an fatigue) is only partially doable by spells now, so I'm not sure yet whether to rework them to use HP-casting spells or not, but that'd be a consistent way to do it. Dragonfire by necessity will likely stay a toggle mutation given its only cost is hunger.

Note that the entirety of the spell list for Paragon of The Veil is still using the old format, but that's because I need to get to them next. That's a very long spell list to handle, easily half of all the spells in Arcana. @.@

You'll likely also see that a lot of Dragonblood's spells inherited from an older character have been converted into the spellcraft and scenario versions instead, consuming fatigue as normal instead of HP. This is thanks to having to split up mutations even further so that a spellcraft scroll or chargen choice doesn't give you the exact same spell as you would via Dragonblood (something I already had to do with PoTV spells when I added The Hermit), so to avoid dumping more mutation IDs in the bin I retained them for the non-dragonblood versions.
