### ISSUE TITLE
NPC being able to wear spell created items

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#85]
If you cast the spell clairvoyance or drain life you get the related item, but you are able to take it of or recast the spell and get more of them, and then give it to a NPC to wear. i dont know if they get the effect properly, and the item expires correctly.

This is more of a "letting you know just in case" issue

**Comment by chaosvolt** [comment]
I'm aware yeah, it should work for NPCs too as far as I'm aware, barring any potential weird shit going on in the AEP code. Being able to cast effect spells on NPCs is intended for all branches of spellcasting except Dragonblood, and use of halos is only because they still need to use item-based hacks to function at all. Eventually, if effects exist to serve all AEP roles, you'll be able to cast Clairvyoance, Drain Life etc directly on your pals.

The only part that's sadly an unavoidable exploit is giving the halos generate by Dragonblood spells to NPCs, which will also be mitigated if all the AEP effects get mitigated by effect flags.

Thank you for the help, regardless. :3
