### ISSUE TITLE
Bounced effect after shooting symbol of judgement

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#92]
After shooting the symbol of judgement, you get the bounced effect
![Screenshot_1](https://user-images.githubusercontent.com/34730575/66722151-c889d480-edcf-11e9-8b28-31550d092a70.jpg)
It disappears after a turn though .

**Comment by chaosvolt** [comment]
Hardcode bug caused by symbol of judgement using the chain-lightning effect. If you didn't accidentally shoot yourself with it while firing on a close-up enemy, than the bug is that this is granting the effect to targets that aren't actually having shots bounce on them.

Either way, even if you ARE hitting yourself with it by accident, there's additionally the bug that the bouncy-effect flag is granting an AI-only effect to the player.

I'm tempted to remove the bounce flag from the symbol of judgement anyway, because my mental image is more that the weapon fires a beam with arcs of electricity branching out from it periodically (plus high single-target damage is the primary balancing factor). This would *technically* fix the specific situation this bug is appearing in, but the underlying cause is a CDDA bug that should be reported to them.
