### ISSUE TITLE
Essence gem, what is it use?

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#93]
As the title says, what is it use, i cant figure it out.
At first i thought it was mean to be used as a magazine but no, unless it is a simple storage. And if that is indeed its only use i dont see much of a point in it. 
![Screenshot_2](https://user-images.githubusercontent.com/34730575/66722250-0e936800-edd1-11e9-9f89-2874be2aefe3.jpg)
Sorry for the rant, but that item use has been irking me for a time.

**Comment by chaosvolt** [comment]
It started mainly as a workaround for the fact that essence is forced to have a minimum volume, and it piles up pretty damn fast. You can wear the essence gem for free, basically reducing the effect of that little annoyance. I tried to test whether there was a way to make it act like a bandolier and have it be faster, but that minimum volume and non-existent weight seems to make 

I'd like to keep playing around with how to make it more useful however, this is something @triffidking has mentioned before too. It's rather hard to give it a solid use beyond a QoL feature that only exists because the code is being nonsensical (it didn't used to have that restriction though).

**Comment by chaosvolt** [comment]
Ahah! Turns out I never did mess around more with `draw_cost`, it seems that reloading now likes to tack on an extra full move's worth of time even for something with no weight and minimum volume, but a worn bandolier lets you replace that extra time with the stated draw cost outright.

![image](https://user-images.githubusercontent.com/11582235/66936053-b17ef880-f002-11e9-909a-6c555152795d.png)
