### ISSUE TITLE
Red potions cause overdosing

### ISSUE THREAD

**Issue by Highmongrel** [chaosvolt/cdda-arcana-mod#94]
Luckily I found it while messing around on a test world, but consuming a red potion currently seems to overdose you on pain killers.

On a side note, white potions seem to tank your stamina now, but I'm not sure if that was intended or not.

**Comment by chaosvolt** [comment]
Ah, I see what happened. When I overhauled the effects recently, I forgot to convert red potion from using `pkill_min` to a negative `pain_min`.

As for white potion, it should probably be stamina recovery, now that I think about it. Even if I did want to make it wear you out faster, it probably should be pinging fatigue instead because stamina is a finicky mess these days.

**Comment by chaosvolt** [comment]
Pffft FFS, I like how the effect menu is smart enough to label a stamina boost as "stamina recovery" but calls a negative pain value just "pain," even though it's sensible enough to suppress the "your body aches" message if it's subtracting pain...

**Comment by chaosvolt** [comment]
Should all be fixed by https://github.com/chaosvolt/cdda-arcana-mod/commit/7c3c367c866775964cfb39e442da42e08653a2b9, thank you and tell me if anything else crops up.
