### ISSUE TITLE
crash from motes of artifice 

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#96]
The motes of artifice from the blessing of open lock, causes a crash if you interact with it from the inventory menu(if you select it and press enter), work as intended if used from the use item menu

**Comment by chaosvolt** [comment]
Wh-

I thought they fixed that bug ages ago. :eyes:

**Comment by chaosvolt** [comment]
I'm testing both versions of the mote of artifice in 0.D-8668-gf7c73e0 [64-bit] (build 9787), and not able to reproduce this bug again.

![image](https://user-images.githubusercontent.com/11582235/67164170-24f37380-f33d-11e9-9a5e-0f64fb8ac5ca.png)

![image](https://user-images.githubusercontent.com/11582235/67164176-376dad00-f33d-11e9-891e-ad6d58dfbda2.png)

I've tested the `a`ction menu, trying to `E`at them (stupid game correctly groks that this comestible is not actually food and thus doesn't actually activate it if you select it, but still thinks it's useful to list it on your food list...), then going to their item description menu from `i`nventory and trying both (`a`ctivate works, `E`at just cancels silently).

However, I HAVE noticed an unexpected bug that wasn't happening last time I tested this: damn things are unlocking doors without being consumed, they used to deplete on use.

Make sure your build is up to date because this is something that was happening several months ago. Unless it's something still happening in linux builds or some other build I lack a machine to test with, this sounds like a 90% chance of the launcher being at work once again.

Thank you regardless, given re-testing has revealed that something has changed with how the item works.
