### ISSUE TITLE
Health needed to cast dragonblood spells

### ISSUE THREAD

**Issue by Ignaramico** [chaosvolt/cdda-arcana-mod#99]
After gaining the dragonblood mutations, i found you needed hp to cast spells, but even after getting the post-threshold and at full health, i cant cast any of them
![Screenshot_4](https://user-images.githubusercontent.com/34730575/68093055-35384200-fe57-11e9-935a-4dbf9d06fd49.jpg)

and after debbugging my self some health, i discovered i that the spells only became castable after getting 400 torso hp
![Screenshot_1](https://user-images.githubusercontent.com/34730575/68093098-a1b34100-fe57-11e9-9a51-41eab4a9dbf4.jpg)
after that the hp left for the torso was 60 points after casting the summon fiend spell

**Comment by chaosvolt** [comment]
Wh-how? I haven't tweaked HP requirements at all since these were implemented, sounds like CDDA is having a math issue with HP-casting spells.

Summon Fiend for example starts off with an HP coast of 20, down to 15 HP at max level. Pinging @korggent as I'm not sure what would make it decide to cost 340 HP instead....

**Comment by chaosvolt** [comment]
![image](https://user-images.githubusercontent.com/11582235/68095707-5f96f900-fe71-11e9-8348-9d30399e8076.png)

Tested this in builds 9850 and 9857, I'm not able to reproduce this. I don't know what could cause that, whether it was only a brief blip of strange behavior in a single build, or what. Update both your build and Arcana, and please tell me if it continues to act up for you, or if you find anything that might suggest a possible cause.

**Comment by Ignaramico** [comment]
for what it seems. the problem is from my save, started a new character and it works perfectly, still no idea of what happened, since i dont think one can affect the cost of spells accidentally from doing something while playing, after clearing myself from the dragon mutations, i can still learn the paragon ones perfectly fine

**Comment by chaosvolt** [comment]
Yeah, nothing comes to mind for a likely cause at all. I'm glad it seems to be a one-off save bug so far. Here's hoping that's the case...

**Comment by adamkad1** [comment]
I hope you are not wearing gloves or somethin like that, spell resource costs can get increased by impediment too

**Comment by chaosvolt** [comment]
Holy shit, that's a thing? I've never seen that occur before.

**Comment by chaosvolt** [comment]
Okay yeah, I looked into it. It seems that only hand encumbrance is a concern here, whereas all other sources of encumbrance are either not relevant to Dragonblood, or else only affect casting time. I think I can easily enough justify slapping NO_HANDS on Dragonblood spells as well, given HP-casting and fatigue-casting are both infinitely more likely to screw the player over if overtaxed than mana-casting.

In fact, the only reason I didn't add NO_HANDS in the first place is because I expected Dragonblood characters to cast bare-handed and/or while wielding a hellfire staff, but it seems that using a magic focus doesn't affect hand encumbrance penalties at all.

It seems that even something as basic as 10 encumbrance seems to render HP-casting useless, even without any claw mutations. Mana-casting in contrast seems to be heavily affected by this as well, but it's far less punishing a penalty, only maybe 50% more or so mana vs. well in excess of 10x cost.

**Comment by chaosvolt** [comment]
Fixed it via https://github.com/chaosvolt/cdda-arcana-mod/commit/8309d2b60d95fe3b7155e12012340f518bfb069e for now. I found out the cause: the way cost scales with hand encumbrance is balanced with mana-casting in mind, and does not change with resource used. This is hilarious if you use stamina (baseline stamina pool is 10 times your expected baseline for mana), punishing for fatigue (max is effectively 400-ish) and CBM (no real baseline, but hitting 1000 and keeping it there consistently is difficult) casters, and completely unusable for HP-casters (baseline is under 100).
